import { useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import type {
  SystemControlEngineDeployment,
  SystemControlEngineDeploymentVersion,
  SystemControlRoutingPool,
  SystemControlRoutingPolicyVersion,
  SystemControlRoutingWorkflowStage,
} from '@qimao-terms-cloud/contracts';
import { Badge, CommandRecovery, EmptyBlock, ErrorBlock, Field, LoadingBlock, Modal, formatDate, useAsyncRead } from './controlPrimitives.js';
import { createRouting, createStableId, getRouting, isUnknownResult, listEngines, listRouting, listVersions, transitionRouting } from './systemApi.js';

const PAGE_SIZE = 20;
const POOLS = ['asr_api', 'ocr_api', 'ocr_self_hosted_worker', 'terms_api'] as const;
type PoolId = typeof POOLS[number];
type Target = SystemControlRoutingPool['targets'][number];
const poolName: Record<PoolId, string> = { asr_api: 'ASR API', ocr_api: 'OCR 云服务', ocr_self_hosted_worker: 'OCR 本地 Worker', terms_api: '术语 API' };
const capabilityForPool = (poolId: PoolId): SystemControlEngineDeployment['capability'] => poolId === 'asr_api' ? 'asr' : poolId === 'terms_api' ? 'terms' : 'screen_text';
const emptyVersionList = { items: [], total: 0, limit: PAGE_SIZE, offset: 0 };
const makePools = (stage: SystemControlRoutingWorkflowStage = 'asr'): SystemControlRoutingPool[] => POOLS.filter((poolId) => stage === 'terms' ? poolId === 'terms_api' : poolId !== 'terms_api').map((poolId) => ({ poolId, targets: [] }));
const roleName: Record<Target['role'], string> = { preferred: '首选', standard: '标准', emergency: '应急' };
const stageName = (stage: SystemControlRoutingWorkflowStage) => stage === 'asr' ? '语音识别' : stage === 'screen_text' ? '画面字' : '术语提取';
const targetIdPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const validateTargetOrder = (rows: Array<{ target: Target }>) => {
  if (rows.length === 1 && rows[0]?.target.role !== 'preferred') return '单目标必须保持“首选”角色。';
  if (rows.length > 1 && rows[0]?.target.role !== 'preferred') return '第 1 个目标必须保持“首选”角色。';
  if (rows.length > 2 && rows.slice(1, -1).some(({ target }) => target.role !== 'standard')) return '中间目标必须保持“标准”角色。';
  if (rows.length > 1 && !['standard', 'emergency'].includes(rows.at(-1)?.target.role ?? '')) return '最后一个目标只能是“标准”或“应急”角色。';
  return null;
};

const PageButtons = ({ offset, total, onChange, label }: { offset: number; total: number; onChange: (next: number) => void; label: string }) => <div className="cp-pagination"><span>{total === 0 ? `0 条${label}` : `${offset + 1}–${Math.min(offset + PAGE_SIZE, total)} / ${total}${label}`}</span><button className="cp-secondary" type="button" disabled={offset === 0} onClick={() => onChange(Math.max(0, offset - PAGE_SIZE))}>上一页</button><button className="cp-secondary" type="button" disabled={offset + PAGE_SIZE >= total} onClick={() => onChange(offset + PAGE_SIZE)}>下一页</button></div>;

const flattenTargets = (pools: readonly SystemControlRoutingPool[]) => pools.flatMap((pool) => pool.targets.map((target) => ({ poolId: pool.poolId, target }))).sort((a, b) => a.target.priority - b.target.priority);
const renumber = (pools: SystemControlRoutingPool[]) => {
  const priorities = new Map(flattenTargets(pools).map(({ target }, index) => [target.routingTargetId, index + 1]));
  return pools.map((pool) => ({ ...pool, targets: pool.targets.map((target) => ({ ...target, priority: priorities.get(target.routingTargetId) ?? target.priority })) }));
};
const updateTarget = (pools: SystemControlRoutingPool[], targetId: string, change: (target: Target) => Target) => pools.map((pool) => ({ ...pool, targets: pool.targets.map((target) => target.routingTargetId === targetId ? change(target) : target) }));
const removeTarget = (pools: SystemControlRoutingPool[], targetId: string) => renumber(pools.map((pool) => ({ ...pool, targets: pool.targets.filter((target) => target.routingTargetId !== targetId) })));
const moveTarget = (pools: SystemControlRoutingPool[], targetId: string, direction: -1 | 1) => { const rows = flattenTargets(pools); const index = rows.findIndex((row) => row.target.routingTargetId === targetId); const next = index + direction; if (index < 0 || next < 0 || next >= rows.length) return pools; [rows[index], rows[next]] = [rows[next]!, rows[index]!]; const byId = new Map(rows.map((row, position) => [row.target.routingTargetId, { ...row.target, priority: position + 1 }])); return pools.map((pool) => ({ ...pool, targets: pool.targets.map((target) => byId.get(target.routingTargetId) ?? target) })); };

const PolicyCard = ({ policy, onSelect }: { policy: SystemControlRoutingPolicyVersion; onSelect: () => void }) => <button className="cp-policy-card" type="button" onClick={onSelect}><div className="cp-row-between"><strong>v{policy.version} · {stageName(policy.workflowStage)}</strong><Badge value={policy.status} /></div><span>{policy.routingVersionId}</span><small>更新时间 {formatDate(policy.updatedAt)}</small></button>;

const VersionChoice = ({ deployment, value, onChange }: { deployment: SystemControlEngineDeployment | null; value: string; onChange: (next: string) => void }) => {
  const [offset, setOffset] = useState(0);
  const query = deployment ? `limit=${PAGE_SIZE}&offset=${offset}` : '';
  const versions = useAsyncRead((signal) => deployment ? listVersions(deployment.deploymentId, query, signal) : Promise.resolve(emptyVersionList), [deployment?.deploymentId, offset]);
  const pageItems = versions.data?.items ?? [];
  useLayoutEffect(() => {
    if (value && versions.data && !pageItems.some((item) => item.versionId === value)) onChange('');
  }, [pageItems, value, versions.data, onChange]);
  return <div>{deployment ? <><Field label="不可变部署版本"><select aria-label="部署版本选择" value={value} onChange={(event) => onChange(event.target.value)}><option value="">请选择服务端版本</option>{pageItems.map((item: SystemControlEngineDeploymentVersion) => <option key={item.versionId} value={item.versionId}>v{item.version} · {item.model} · {item.capabilitiesSnapshot.executionKind === 'self_hosted_worker' ? '本地' : '云'}</option>)}</select></Field><p className="cp-muted">部署：{deployment.displayName} · 服务端版本 {versions.data?.total ?? '—'} 条</p><PageButtons offset={versions.data?.offset ?? offset} total={versions.data?.total ?? 0} onChange={setOffset} label="版本" />{versions.error ? <ErrorBlock error={versions.error} onRetry={() => void versions.reload()} busy={versions.refreshing} /> : null}</> : <p className="cp-muted">先选择服务端部署，再读取其版本分页。</p>}</div>;
};

const TargetEditor = ({ pool, target, deployments, onChange, onRemove, onMove }: { pool: PoolId; target: Target; deployments: SystemControlEngineDeployment[]; onChange: (target: Target) => void; onRemove: () => void; onMove: (direction: -1 | 1) => void }) => {
  const capability = capabilityForPool(pool);
  const [deploymentId, setDeploymentId] = useState('');
  const options = deployments.filter((deployment) => deployment.capability === capability);
  const deployment = options.find((item) => item.deploymentId === deploymentId) ?? null;
  useEffect(() => {
    if (deploymentId && !options.some((item) => item.deploymentId === deploymentId)) {
      setDeploymentId('');
      if (target.deploymentVersionId) onChange({ ...target, deploymentVersionId: '' });
    }
  }, [deploymentId, deployments, options, onChange, target]);
  return <article className="cp-subcard routing-target-editor"><div className="cp-row-between"><strong>目标 {target.priority}</strong><div className="cp-row-actions"><button className="cp-link" type="button" onClick={() => onMove(-1)} disabled={target.priority === 1}>上移</button><button className="cp-link" type="button" onClick={() => onMove(1)}>下移</button><button className="cp-link" type="button" onClick={onRemove}>删除</button></div></div><div className="cp-form-grid"><Field label="部署"><select aria-label={`目标${target.priority}部署选择`} value={deploymentId} onChange={(event) => { setDeploymentId(event.target.value); onChange({ ...target, deploymentVersionId: '' }); }}><option value="">请选择服务端部署</option>{options.map((item) => <option key={item.deploymentId} value={item.deploymentId} disabled={item.status === 'disabled'}>{item.displayName} · {item.executionKind === 'self_hosted_worker' ? '本地' : '云'} · {item.status === 'enabled' ? '可用' : '已停用'}</option>)}</select></Field><Field label="业务角色"><select aria-label={`目标${target.priority}角色`} value={target.role} onChange={(event) => onChange({ ...target, role: event.target.value as Target['role'] })}><option value="preferred">首选</option><option value="standard">标准</option><option value="emergency">应急</option></select></Field></div><VersionChoice deployment={deployment} value={target.deploymentVersionId} onChange={(deploymentVersionId) => onChange({ ...target, deploymentVersionId })} /><div className="cp-form-grid"><Field label="最大并发"><input aria-label={`目标${target.priority}最大并发`} type="number" min="1" value={target.maxConcurrentJobs} onChange={(event) => onChange({ ...target, maxConcurrentJobs: Number(event.target.value) })} /></Field><Field label="单项目上限"><input aria-label={`目标${target.priority}单项目上限`} type="number" min="1" value={target.perProjectMax} onChange={(event) => onChange({ ...target, perProjectMax: Number(event.target.value) })} /></Field><Field label="队列上限"><input aria-label={`目标${target.priority}队列上限`} type="number" min="0" value={target.queueLimit} onChange={(event) => onChange({ ...target, queueLimit: Number(event.target.value) })} /></Field></div></article>;
};

const TargetRows = ({ pools }: { pools: readonly SystemControlRoutingPool[] }) => { const rows = flattenTargets(pools); return <div className="cp-table-wrap routing-target-table"><table className="cp-table"><thead><tr><th>顺序</th><th>真实部署版本</th><th>角色</th><th>执行位置</th><th>容量</th><th>连接检查</th></tr></thead><tbody>{rows.map(({ poolId, target }) => <tr key={target.routingTargetId}><td><strong>{target.priority}</strong></td><td><code>{target.deploymentVersionId}</code></td><td>{roleName[target.role]}</td><td>{poolName[poolId]}</td><td>并发 {target.maxConcurrentJobs} · 单项目 {target.perProjectMax} · 队列 {target.queueLimit}</td><td>服务端事实</td></tr>)}</tbody></table></div>; };

export const RoutingPage = ({ onNavigate }: { onNavigate: (path: string) => void }) => {
  const [stage, setStage] = useState<SystemControlRoutingWorkflowStage>('asr');
  const [status, setStatus] = useState('');
  const [routeOffset, setRouteOffset] = useState(0);
  const [engineOffset, setEngineOffset] = useState(0);
  const [showEditor, setShowEditor] = useState(false);
  const [selected, setSelected] = useState<SystemControlRoutingPolicyVersion | null>(null);
  const [draft, setDraft] = useState(() => makePools('asr'));
  const [busy, setBusy] = useState(false);
  const [actionError, setActionError] = useState<unknown>(null);
  const [pendingRecovery, setPendingRecovery] = useState<string | null>(null);
  const [validationError, setValidationError] = useState('');
  const titleRef = useRef<HTMLHeadingElement>(null);
  const draftTriggerRef = useRef<HTMLButtonElement>(null);
  const routeQuery = useMemo(() => { const params = new URLSearchParams({ environment: 'development', workflowStage: stage, limit: String(PAGE_SIZE), offset: String(routeOffset) }); if (status) params.set('status', status); return params.toString(); }, [stage, status, routeOffset]);
  const activeQuery = useMemo(() => new URLSearchParams({ environment: 'development', workflowStage: stage, status: 'active', limit: '1', offset: '0' }).toString(), [stage]);
  const routes = useAsyncRead((signal) => listRouting(routeQuery, signal), [routeQuery]);
  const activeRoutes = useAsyncRead((signal) => listRouting(activeQuery, signal), [activeQuery]);
  const engines = useAsyncRead((signal) => listEngines(`capability=${capabilityForPool(stage === 'terms' ? 'terms_api' : stage === 'asr' ? 'asr_api' : 'ocr_api')}&limit=${PAGE_SIZE}&offset=${engineOffset}`, signal), [stage, engineOffset]);
  useEffect(() => { setRouteOffset(0); setSelected(null); setPendingRecovery(null); setActionError(null); setShowEditor(false); setDraft(makePools(stage)); }, [stage, status]);
  const active = activeRoutes.data?.items[0] ?? null;
  const history = routes.data?.items.filter((item) => item.status !== 'active') ?? [];
  const addTarget = (poolId: PoolId) => { const rows = flattenTargets(draft); if (rows.length >= 8) return; const target: Target = { routingTargetId: createStableId(), deploymentVersionId: '', priority: rows.length + 1, role: rows.length === 0 ? 'preferred' : 'standard', maxConcurrentJobs: 1, perProjectMax: 1, queueLimit: 0 }; setDraft((current) => current.map((pool) => pool.poolId === poolId ? { ...pool, targets: [...pool.targets, target] } : pool)); };
  const saveDraft = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setValidationError(''); const rows = flattenTargets(draft); if (rows.length < 1 || rows.length > 8) { setValidationError('请配置 1–8 个真实部署目标。'); return; } if (rows.some(({ target }) => !target.deploymentVersionId || !targetIdPattern.test(target.deploymentVersionId))) { setValidationError('每个目标必须先选择服务端真实部署版本；分页切换后已失效的选择不能提交。'); return; } if (new Set(rows.map(({ target }) => target.deploymentVersionId)).size !== rows.length) { setValidationError('同一工作流不能重复引用部署版本。'); return; } const priorities = rows.map(({ target }) => target.priority); if (new Set(priorities).size !== rows.length || priorities.some((value, index) => value !== index + 1)) { setValidationError('目标顺序必须是服务端连续的 1–8。'); return; } const roleError = validateTargetOrder(rows); if (roleError) { setValidationError(roleError); return; } setBusy(true); setActionError(null); const routingVersionId = createStableId(); try { await createRouting({ routingVersionId, environment: 'development', workflowStage: stage, pools: draft }, createStableId()); setShowEditor(false); await routes.reload(); await activeRoutes.reload(); } catch (error) { setActionError(error); if (isUnknownResult(error)) { setPendingRecovery(routingVersionId); setShowEditor(false); } else { setPendingRecovery(null); await Promise.all([routes.reload(), activeRoutes.reload(), engines.reload()]); } } finally { setBusy(false); } };
  const transition = async (action: 'test' | 'impact-check' | 'approve') => { if (!selected) return; setBusy(true); setActionError(null); try { const updated = await transitionRouting(selected.routingVersionId, action, createStableId()); setSelected(updated); await Promise.all([routes.reload(), activeRoutes.reload()]); } catch (error) { setActionError(error); setPendingRecovery(null); try { setSelected(await getRouting(selected.routingVersionId)); } catch { /* 保留服务端错误 */ } finally { await Promise.all([routes.reload(), activeRoutes.reload()]); } } finally { setBusy(false); } };
  const recover = async () => { if (!pendingRecovery) return; setBusy(true); setActionError(null); try { setSelected(await getRouting(pendingRecovery)); setPendingRecovery(null); await Promise.all([routes.reload(), activeRoutes.reload()]); titleRef.current?.focus(); } catch (error) { setActionError(error); } finally { setBusy(false); } };
  const openEditor = (trigger: HTMLButtonElement) => { draftTriggerRef.current = trigger; setActionError(null); setValidationError(''); setDraft(makePools(stage)); setEngineOffset(0); setShowEditor(true); };
  return <div className="cp-page" data-testid="routing-page"><header className="cp-page-head"><div><h1 ref={titleRef} tabIndex={-1}>路由与调度</h1><p>目标顺序、部署版本和容量只读取或提交服务端草稿；人工处理是全部真实目标耗尽后的领域出口。</p></div><button className="cp-primary" type="button" onClick={(event) => openEditor(event.currentTarget)}>新建路由草稿</button></header>
    <div className="cp-tabs" role="tablist" aria-label="工作流阶段">{(['asr', 'screen_text', 'terms'] as const).map((item) => <button key={item} className={stage === item ? 'selected' : ''} type="button" role="tab" aria-selected={stage === item} onClick={() => setStage(item)}>{stageName(item)}</button>)}</div>
    <section className="cp-toolbar"><select aria-label="路由状态筛选" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">全部状态</option>{['draft', 'testing', 'impact_checked', 'approved', 'active', 'retired'].map((item) => <option key={item} value={item}>{item}</option>)}</select></section>
    {actionError && !showEditor ? <ErrorBlock error={actionError} showRetry={false} focusOnMount={!pendingRecovery} title="操作失败，服务端事实未被伪造。" /> : null}{pendingRecovery ? <CommandRecovery kind="routing" identity={pendingRecovery} onRecover={() => void recover()} busy={busy} /> : null}
    <div className="cp-split-grid"><section className="cp-panel"><div className="cp-section-head"><h2>当前生效</h2><Badge value={activeRoutes.error && !activeRoutes.data ? 'unknown' : active?.status ?? 'unknown'} /></div>{activeRoutes.error ? <ErrorBlock error={activeRoutes.error} stale={Boolean(activeRoutes.data)} onRetry={() => activeRoutes.reload(() => titleRef.current?.focus())} busy={activeRoutes.refreshing} /> : null}{activeRoutes.loading && !activeRoutes.data ? <LoadingBlock /> : active ? <><PolicyCard policy={active} onSelect={() => setSelected(active)} /><TargetRows pools={active.pools} /></> : <EmptyBlock title="暂无 active 路由" detail="服务端没有默认 active；请显式创建并推进一份草稿。" />}</section><section className="cp-panel"><div className="cp-section-head"><h2>草稿与历史</h2><span className="cp-muted">服务端 total {routes.data?.total ?? '—'}</span></div>{routes.error ? <ErrorBlock error={routes.error} stale={Boolean(routes.data)} onRetry={() => routes.reload(() => titleRef.current?.focus())} busy={routes.refreshing} /> : null}{routes.loading && !routes.data ? <LoadingBlock /> : history.length ? history.map((item) => <PolicyCard key={item.routingVersionId} policy={item} onSelect={() => setSelected(item)} />) : <EmptyBlock title="暂无草稿或历史" detail="没有浏览器默认配置，也没有匿名样例。" />}{routes.data ? <PageButtons offset={routes.data.offset} total={routes.data.total} onChange={setRouteOffset} label="路由" /> : null}</section></div>
    {selected ? <section className="cp-panel"><div className="cp-section-head"><div><h2>路由 v{selected.version}</h2><span className="cp-muted">{selected.routingVersionId} · 更新于 {formatDate(selected.updatedAt)}</span></div><Badge value={selected.status} /></div><TargetRows pools={selected.pools} /><div className="cp-subcard"><strong>目标耗尽后的处理</strong><p className="cp-muted">全部真实部署目标均已确定失败后进入领域人工工作台；人工处理不编号、不做连接检查、不使用引擎容量。</p></div>{selected.impact ? <div className={`cp-impact ${selected.impact.hardBlocks.length ? 'blocked' : ''}`}><strong>{selected.impact.hardBlocks.length ? '影响检查存在硬阻断' : '影响检查已返回'}</strong><span>活动任务 {selected.impact.activeTaskCount} · 需对账 {selected.impact.reconciliationRequiredTaskCount} · 失败测试 {selected.impact.failingConnectionTestCount}</span>{selected.impact.hardBlocks.map((block) => <p key={block}>阻断：{block}</p>)}</div> : null}<div className="cp-row-actions">{selected.status === 'draft' ? <button className="cp-secondary" type="button" onClick={() => void transition('test')} disabled={busy}>进入测试</button> : null}{selected.status === 'testing' ? <button className="cp-secondary" type="button" onClick={() => void transition('impact-check')} disabled={busy}>检查影响</button> : null}{selected.status === 'impact_checked' ? <button className="cp-primary" type="button" onClick={() => void transition('approve')} disabled={busy || Boolean(selected.impact?.hardBlocks.length)}>批准变更</button> : null}<button className="cp-secondary" type="button" onClick={() => onNavigate('/changes')}>前往变更与审计</button></div></section> : null}
    {showEditor ? <Modal title="新建路由草稿" onUnmountFocus={() => draftTriggerRef.current?.focus()} onClose={() => { if (!busy) { setActionError(null); setValidationError(''); setShowEditor(false); } }} onSubmit={saveDraft} busy={busy} submitLabel="创建草稿"><p className="cp-notice">目标必须引用服务端已登记的真实部署版本；编辑只形成草稿，发布由变更页完成。</p>{validationError ? <div className="cp-state cp-error" role="alert" tabIndex={-1}><strong>草稿尚未提交</strong><span>{validationError}</span></div> : null}{actionError ? <ErrorBlock error={actionError} showRetry={false} focusOnMount={!busy} title="操作失败，服务端事实未被伪造。" /> : null}{engines.error ? <ErrorBlock error={engines.error} onRetry={() => void engines.reload()} busy={engines.refreshing} /> : null}{engines.loading && !engines.data ? <LoadingBlock /> : <>{POOLS.map((poolId) => { const pool = draft.find((item) => item.poolId === poolId); const allowed = stage === 'terms' ? poolId === 'terms_api' : stage === 'asr' ? poolId === 'asr_api' : poolId !== 'asr_api' && poolId !== 'terms_api'; return allowed && pool ? <section className="cp-subcard" key={poolId}><div className="cp-section-head"><h3>{poolName[poolId]}</h3><button className="cp-secondary" type="button" onClick={() => addTarget(poolId)} disabled={flattenTargets(draft).length >= 8}>新增真实目标</button></div>{pool.targets.length ? pool.targets.map((target) => <TargetEditor key={target.routingTargetId} pool={poolId} target={target} deployments={engines.data?.items ?? []} onChange={(next) => setDraft((current) => updateTarget(current, target.routingTargetId, () => next))} onRemove={() => setDraft((current) => removeTarget(current, target.routingTargetId))} onMove={(direction) => setDraft((current) => moveTarget(current, target.routingTargetId, direction))} />) : <EmptyBlock title="尚未配置目标" detail="显式新增并选择服务端部署版本。" />}</section> : null; })}</>}{engines.data ? <PageButtons offset={engines.data.offset} total={engines.data.total} onChange={setEngineOffset} label="部署" /> : null}</Modal> : null}
  </div>;
};
