import { useEffect, useRef, useState, type FormEvent, type RefObject } from 'react';
import type {
  SystemControlCreateEvaluationRunBody,
  SystemControlCreateOptimizationRunBody,
  SystemControlOptimizationRun,
  SystemControlOptimizationRunList,
  SystemControlStrategyCandidate,
  SystemControlStrategyCandidateDecisionBody,
  SystemControlStrategyCandidateList,
  SystemControlEvaluationRun,
  SystemControlEvaluationRunList,
  SystemControlStrategyModule,
} from '@qimao-terms-cloud/contracts';
import { CommandRecovery, EmptyBlock, ErrorBlock, Field, LoadingBlock, Modal, formatDate, useAsyncRead } from './controlPrimitives.js';
import { ControlApiError, createStableId, isDeterministicConflict, isUnknownResult } from './systemApi.js';
import {
  createStrategyEvaluation,
  createStrategyOptimizationRun,
  decideStrategyCandidate,
  getStrategyCandidate,
  getStrategyCandidateDecision,
  getStrategyEvaluation,
  getStrategyOptimizationRun,
  listStrategyCandidates,
  listStrategyEvaluations,
  listStrategyOptimizationRuns,
  listStrategyArtifacts,
  listStrategyVersions,
} from './strategyApi.js';

const MODULES: Array<{ id: SystemControlStrategyModule; label: string }> = [
  { id: 'terms', label: '术语' }, { id: 'pre_review', label: '前置审改' },
  { id: 'screen_text', label: '画面字' }, { id: 'subtitle_acceptance', label: '字幕验收' },
];
const statusText: Record<string, string> = { queued: '排队中', running: '运行中', succeeded: '已完成', failed: '失败', unknown: '结果未知', proposed: '待审查', edited: '已编辑', rejected: '已驳回', evaluation_ready: '待评测' };
const shortId = (value: string | null | undefined) => value ? `${value.slice(0, 8)}…${value.slice(-4)}` : '—';
const pageQuery = (input: Record<string, string | number | undefined>) => { const q = new URLSearchParams(); Object.entries(input).forEach(([k, v]) => { if (v !== undefined && v !== '') q.set(k, String(v)); }); return q.toString(); };
type WaveTab = 'runs' | 'candidates' | 'evaluations' | 'release';
type Recovery = { kind: 'strategy-run' | 'strategy-decision' | 'strategy-evaluation'; identity: string; error: unknown; runId?: string; decisionId?: string; evaluationRunId?: string; candidateId?: string; originRunId?: string | null; selectRunOnSuccess?: boolean };
type Action = { kind: 'edit' | 'reject' | 'restore' | 'send_to_evaluation'; candidate: SystemControlStrategyCandidate; decisionId: string; key: string } | null;

export const StrategyWaveB = ({ tab, titleRef, onTab }: { tab: WaveTab; titleRef: RefObject<HTMLHeadingElement | null>; onTab: (tab: WaveTab) => void }) => {
  const [page, setPage] = useState(0); const [statusFilter, setStatusFilter] = useState('');
  const [selectedRunId, setSelectedRunId] = useState<string | null>(null); const [selectedCandidateId, setSelectedCandidateId] = useState<string | null>(null); const [selectedEvaluationId, setSelectedEvaluationId] = useState<string | null>(null);
  const [runModal, setRunModal] = useState(false); const [action, setAction] = useState<Action>(null); const [evaluationModal, setEvaluationModal] = useState(false);
  const [runArtifactId, setRunArtifactId] = useState(''); const [runBaseVersionId, setRunBaseVersionId] = useState('');
  const [busy, setBusy] = useState(false); const [actionError, setActionError] = useState<unknown>(null); const [recovery, setRecovery] = useState<Recovery | null>(null); const [recoveryBusy, setRecoveryBusy] = useState(false); const [statusMessage, setStatusMessage] = useState('');
  const [candidateOverride, setCandidateOverride] = useState<SystemControlStrategyCandidate | null>(null);
  const [evaluationCandidateId, setEvaluationCandidateId] = useState<string | null>(null);
  const runHeading = useRef<HTMLHeadingElement>(null); const candidateHeading = useRef<HTMLHeadingElement>(null); const evaluationHeading = useRef<HTMLHeadingElement>(null);
  const suppressRunModalFocus = useRef(false);
  const identityRef = useRef({ tab, selectedRunId, selectedCandidateId, selectedEvaluationId, page, statusFilter, evaluationCandidateId });

  const runQuery = pageQuery({ status: statusFilter || undefined, limit: 20, offset: page * 20 });
  const runs = useAsyncRead((signal) => tab === 'runs' || tab === 'candidates' ? listStrategyOptimizationRuns(runQuery, signal) : Promise.resolve<SystemControlOptimizationRunList>({ items: [], total: 0, limit: 20, offset: 0 }), [tab, runQuery], { identity: `strategy-runs:${tab}:${runQuery}` });
  const candidates = useAsyncRead((signal) => tab === 'candidates' && selectedRunId ? listStrategyCandidates(pageQuery({ runId: selectedRunId, limit: 20, offset: page * 20 }), signal) : Promise.resolve<SystemControlStrategyCandidateList>({ items: [], total: 0, limit: 20, offset: 0 }), [tab, selectedRunId, page], { identity: `strategy-candidates:${tab}:${selectedRunId}:${page}` });
  const evaluations = useAsyncRead((signal) => tab === 'evaluations' ? listStrategyEvaluations(pageQuery({ status: statusFilter || undefined, limit: 20, offset: page * 20 }), signal) : Promise.resolve<SystemControlEvaluationRunList>({ items: [], total: 0, limit: 20, offset: 0 }), [tab, statusFilter, page], { identity: `strategy-evaluations:${tab}:${statusFilter}:${page}` });
  const runDetail = useAsyncRead((signal) => selectedRunId && tab === 'runs' ? getStrategyOptimizationRun(selectedRunId, signal) : Promise.resolve<SystemControlOptimizationRun | null>(null), [tab, selectedRunId], { identity: `strategy-run:${tab}:${selectedRunId ?? 'none'}` });
  const candidateDetail = useAsyncRead((signal) => selectedCandidateId && tab === 'candidates' ? getStrategyCandidate(selectedCandidateId, signal) : Promise.resolve<SystemControlStrategyCandidate | null>(null), [tab, selectedCandidateId], { identity: `strategy-candidate:${tab}:${selectedCandidateId ?? 'none'}` });
  const evaluationDetail = useAsyncRead((signal) => selectedEvaluationId && tab === 'evaluations' ? getStrategyEvaluation(selectedEvaluationId, signal) : Promise.resolve<SystemControlEvaluationRun | null>(null), [tab, selectedEvaluationId], { identity: `strategy-evaluation:${tab}:${selectedEvaluationId ?? 'none'}` });
  const activeRead = tab === 'runs' ? runs : tab === 'candidates' ? candidates : evaluations;
  const runArtifacts = useAsyncRead((signal) => tab === 'runs' && runModal ? listStrategyArtifacts('limit=100&offset=0&sort=updated_desc', signal) : Promise.resolve({ items: [], total: 0, limit: 100, offset: 0 }), [tab, runModal], { identity: `strategy-run-artifacts:${tab}:${runModal}` });
  const runVersions = useAsyncRead((signal) => tab === 'runs' && runModal && runArtifactId ? listStrategyVersions(runArtifactId, 'limit=100&offset=0', signal) : Promise.resolve(null), [tab, runModal, runArtifactId], { identity: `strategy-run-versions:${tab}:${runModal}:${runArtifactId || 'none'}` });
  const firstArtifactId = runArtifacts.data?.items[0]?.artifactId ?? '';
  const firstVersionId = runVersions.data?.items[0]?.versionId ?? '';
  const activeCandidate = candidateOverride ?? candidateDetail.data;
  const candidateWriteLocked = tab !== 'candidates' || busy || Boolean(candidates.loading || candidates.refreshing || (candidates.error && candidates.data !== null) || candidateDetail.loading || candidateDetail.refreshing || candidateDetail.error || (recovery?.kind === 'strategy-decision'));

  const clearCandidateContext = () => { setSelectedCandidateId(null); setCandidateOverride(null); setEvaluationCandidateId(null); setAction(null); setEvaluationModal(false); };

  useEffect(() => { setPage(0); setStatusFilter(''); setSelectedRunId(null); clearCandidateContext(); setSelectedEvaluationId(null); setRecovery(null); setActionError(null); setRunArtifactId(''); setRunBaseVersionId(''); }, [tab]);
  useEffect(() => { if (runModal && !runArtifactId && runArtifacts.data?.items[0]) setRunArtifactId(runArtifacts.data.items[0].artifactId); }, [runModal, runArtifactId, runArtifacts.data]);
  useEffect(() => { if (runModal && runVersions.data?.items[0] && !runBaseVersionId) setRunBaseVersionId(runVersions.data.items[0].versionId); }, [runModal, runVersions.data, runBaseVersionId]);
  useEffect(() => { if (tab === 'candidates' && !selectedRunId && runs.data?.items[0]) setSelectedRunId(runs.data.items[0].runId); }, [tab, selectedRunId, runs.data]);
  useEffect(() => { if (candidateDetail.data && candidateDetail.data.candidateId === selectedCandidateId) setCandidateOverride(candidateDetail.data); }, [candidateDetail.data, selectedCandidateId]);
  useEffect(() => { if (tab === 'runs' && runDetail.data) runHeading.current?.focus(); }, [tab, runDetail.data]);
  useEffect(() => { if (tab === 'candidates' && candidateOverride) candidateHeading.current?.focus(); }, [tab, candidateOverride]);
  useEffect(() => { if (tab === 'evaluations' && evaluationDetail.data) evaluationHeading.current?.focus(); }, [tab, evaluationDetail.data]);
  useEffect(() => { if (tab === 'candidates') { clearCandidateContext(); setRecovery(null); } }, [selectedRunId, page]);
  useEffect(() => { identityRef.current = { tab, selectedRunId, selectedCandidateId, selectedEvaluationId, page, statusFilter, evaluationCandidateId }; }, [tab, selectedRunId, selectedCandidateId, selectedEvaluationId, page, statusFilter, evaluationCandidateId]);

  const reloadAll = () => { activeRead.reload(); if (tab === 'runs') runDetail.reload(); if (tab === 'candidates') { candidates.reload(); candidateDetail.reload(); } if (tab === 'evaluations') { evaluations.reload(); evaluationDetail.reload(); } };
  const recoverCommand = async (requested?: Recovery) => {
    const target = requested ?? recovery; if (!target) return; setRecovery(target); setRecoveryBusy(true);
    const stillCurrent = () => { const current = identityRef.current; if (target.kind === 'strategy-run') return current.tab === 'runs' && (target.selectRunOnSuccess ? current.selectedRunId === target.originRunId : current.selectedRunId === target.runId); return current.tab === 'candidates' && current.selectedCandidateId === target.candidateId; };
    try {
      if (target.kind === 'strategy-run' && target.runId) { await getStrategyOptimizationRun(target.runId); if (!stillCurrent()) return; if (target.selectRunOnSuccess) { setSelectedRunId(target.runId); runs.reload(); setRecovery(null); queueMicrotask(() => runHeading.current?.focus()); } else { runDetail.reload(); runs.reload(); setRecovery(null); runHeading.current?.focus(); } }
      else if (target.kind === 'strategy-decision' && target.decisionId) { const result = await getStrategyCandidateDecision(target.decisionId); if (!stillCurrent()) return; setCandidateOverride(result.afterSnapshot); candidates.reload(); setRecovery(null); candidateHeading.current?.focus(); }
      else if (target.kind === 'strategy-evaluation' && target.evaluationRunId) { await getStrategyEvaluation(target.evaluationRunId); if (!stillCurrent()) return; evaluations.reload(); candidates.reload(); setRecovery(null); candidateHeading.current?.focus(); }
    } catch (error) { setRecovery((current) => current?.identity === target.identity ? { ...current, error } : current); }
    finally { setRecoveryBusy(false); }
  };
  const createRun = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget); const runId = createStableId(); const key = createStableId(); setBusy(true); setActionError(null);
    const artifactId = (runArtifactId || String(form.get('artifactId') ?? '') || firstArtifactId).trim(); const baseVersionId = (runBaseVersionId || String(form.get('baseVersionId') ?? '') || firstVersionId).trim();
    if (!artifactId || !baseVersionId) { setActionError(new ControlApiError('请先选择服务端策略资产和固定基线版本。', { status: 422, retryable: false })); setBusy(false); return; }
    const body: SystemControlCreateOptimizationRunBody = { runId, artifactId, baseVersionId, module: String(form.get('module') ?? 'terms') as SystemControlStrategyModule, projectId: String(form.get('projectId') ?? '').trim() || null, from: String(form.get('from') ?? '').trim() ? new Date(String(form.get('from'))).toISOString() : null, to: String(form.get('to') ?? '').trim() ? new Date(String(form.get('to'))).toISOString() : null, minEvidenceCount: Number(form.get('minEvidenceCount') ?? 0), maxEvents: Number(form.get('maxEvents') ?? 100), budgetCny: String(form.get('budgetCny') ?? '0.000000') };
    try { await createStrategyOptimizationRun(body, key); setRunModal(false); setStatusMessage('优化运行已提交；候选只来自服务端事实。'); runs.reload(); setSelectedRunId(runId); queueMicrotask(() => titleRef.current?.focus()); }
    catch (error) { if (isUnknownResult(error)) { suppressRunModalFocus.current = true; setRecovery({ kind: 'strategy-run', identity: runId, runId, originRunId: selectedRunId, selectRunOnSuccess: true, error }); setRunModal(false); } else { suppressRunModalFocus.current = false; setActionError(error); if (isDeterministicConflict(error)) { setRunModal(false); runs.reload(); } } }
    finally { setBusy(false); }
  };
  const submitDecision = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (!action) return; const form = new FormData(event.currentTarget); const body: SystemControlStrategyCandidateDecisionBody = { decisionId: action.decisionId, expectedRevision: action.candidate.revision, action: action.kind };
    if (action.kind === 'edit') body.title = String(form.get('title') ?? '').trim();
    if (action.kind === 'edit') { body.rationale = String(form.get('rationale') ?? '').trim(); body.proposal = { operation: 'review_when_changed', target: String(form.get('target') ?? '').trim(), value: String(form.get('value') ?? '').trim(), notes: String(form.get('notes') ?? '').trim() }; }
    if (action.kind === 'reject') body.rationale = `${String(form.get('reason') ?? '人工复核')}: ${String(form.get('note') ?? '').trim()}`;
    setBusy(true); setActionError(null);
    try { const next = await decideStrategyCandidate(action.candidate.candidateId, body, action.key); setCandidateOverride(next); setAction(null); setStatusMessage('候选决定已保存；生产规则没有改变。'); candidates.reload(); queueMicrotask(() => candidateHeading.current?.focus()); }
    catch (error) { if (isUnknownResult(error)) { setRecovery({ kind: 'strategy-decision', identity: action.decisionId, decisionId: action.decisionId, candidateId: action.candidate.candidateId, error }); setAction(null); } else { setActionError(error); if (isDeterministicConflict(error)) { setAction(null); candidates.reload(); } } }
    finally { setBusy(false); }
  };
  const createEvaluationRun = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const candidateId = evaluationCandidateId; if (!candidateId || candidateWriteLocked) return; const evaluationRunId = createStableId(); const body: SystemControlCreateEvaluationRunBody = { evaluationRunId, candidateIds: [candidateId], budgetCny: String(new FormData(event.currentTarget).get('budgetCny') ?? '0.000000') }; setBusy(true); setActionError(null);
    try { await createStrategyEvaluation(body, createStableId()); setEvaluationModal(false); setEvaluationCandidateId(null); setStatusMessage('离线评测已提交；结果仍需人工判断。'); evaluations.reload(); setSelectedEvaluationId(evaluationRunId); evaluationHeading.current?.focus(); }
    catch (error) { if (isUnknownResult(error)) { setRecovery({ kind: 'strategy-evaluation', identity: evaluationRunId, evaluationRunId, candidateId, error }); setEvaluationModal(false); } else { setActionError(error); if (isDeterministicConflict(error)) { setEvaluationModal(false); evaluations.reload(); } } }
    finally { setBusy(false); }
  };

  if (tab === 'release') return <section className="cp-panel strategy-wave-locked"><h2 ref={titleRef} tabIndex={-1}>批准与发布</h2><p>Wave C 尚未启用。当前只支持零网络优化、候选审查和离线评测；不会批准、发布或改变生产规则。</p></section>;
  const stale = Boolean(activeRead.error && activeRead.data !== null);
  return <>
       <section className="cp-panel strategy-wave-panel"><div className="cp-section-head"><div><h2 ref={titleRef} tabIndex={-1}>{tab === 'runs' ? '优化运行' : tab === 'candidates' ? '学习候选' : '离线评测'}</h2><p>服务端事实、稳定身份和零网络处理；浏览器不推算候选、成本或评测结果。</p></div><div className="cp-actions"><button className="cp-secondary" type="button" onClick={reloadAll} disabled={activeRead.refreshing}>重新读取</button>{tab === 'runs' ? <button className="cp-primary" type="button" onClick={() => { suppressRunModalFocus.current = false; setActionError(null); setRunModal(true); }} disabled={stale}>新建优化运行</button> : null}</div></div>
      {activeRead.error ? <ErrorBlock error={activeRead.error} stale={stale} busy={activeRead.refreshing} onRetry={() => activeRead.reload(() => titleRef.current?.focus())} focusOnMount={!activeRead.data} /> : null}
       {recovery && recovery.kind !== 'strategy-decision' && !(recovery.kind === 'strategy-run' && tab === 'runs' && selectedRunId === recovery.runId && runDetail.data?.status === 'unknown') ? <CommandRecovery kind={recovery.kind} identity={recovery.identity} onRecover={() => void recoverCommand()} busy={recoveryBusy} error={recovery.error} /> : null}
      {actionError && !runModal && !action && !evaluationModal ? <ErrorBlock error={actionError} title="本次操作未保存" showRetry={false} focusOnMount /> : null}
      {activeRead.loading && activeRead.data === null ? <LoadingBlock label="读取策略 Wave B 服务端事实…" /> : null}
       {tab === 'runs' ? <RunList data={runs.data} selected={selectedRunId} onSelect={(id) => { setSelectedRunId(id); clearCandidateContext(); setRecovery(null); setActionError(null); }} page={page} setPage={(next) => { setSelectedRunId(null); clearCandidateContext(); setRecovery(null); setPage(next); }} status={statusFilter} setStatus={(next) => { setSelectedRunId(null); clearCandidateContext(); setRecovery(null); setStatusFilter(next); setPage(0); }} /> : null}
       {tab === 'candidates' ? <CandidateList data={candidates.data} runs={runs.data} selectedRunId={selectedRunId} onRun={(id) => { setSelectedRunId(id); clearCandidateContext(); setRecovery(null); setActionError(null); setPage(0); }} selected={selectedCandidateId} onSelect={(id) => { setSelectedCandidateId(id); setCandidateOverride(null); setEvaluationCandidateId(null); setAction(null); setRecovery(null); setActionError(null); }} page={page} setPage={(next) => { clearCandidateContext(); setRecovery(null); setActionError(null); setPage(next); }} /> : null}
       {tab === 'evaluations' ? <EvaluationList data={evaluations.data} selected={selectedEvaluationId} onSelect={(id) => { setSelectedEvaluationId(id); setRecovery(null); setActionError(null); }} page={page} setPage={(next) => { setSelectedEvaluationId(null); setRecovery(null); setPage(next); }} status={statusFilter} setStatus={(next) => { setSelectedEvaluationId(null); setRecovery(null); setStatusFilter(next); setPage(0); }} /> : null}
    </section>
     {tab === 'runs' && selectedRunId && runDetail.data ? <section className="cp-panel strategy-detail-panel"><h3 ref={runHeading} tabIndex={-1}>优化运行 {shortId(runDetail.data!.runId)}</h3><RunDetail run={runDetail.data!} onReload={() => runDetail.reload()} />{runDetail.data!.status === 'unknown' ? <CommandRecovery kind="strategy-run" identity={runDetail.data!.runId} onRecover={() => void recoverCommand({ kind: 'strategy-run', identity: runDetail.data!.runId, runId: runDetail.data!.runId, error: null })} busy={recoveryBusy} error={recovery?.kind === 'strategy-run' ? recovery.error : undefined} /> : null}</section> : null}
     {tab === 'candidates' && activeCandidate ? <section className="cp-panel strategy-detail-panel"><h3 ref={candidateHeading} tabIndex={-1}>候选详情 {shortId(activeCandidate.candidateId)}</h3><CandidateDetail candidate={activeCandidate} readOnly={candidateWriteLocked} onAction={(kind) => { if (!candidateWriteLocked) { setActionError(null); setAction({ kind, candidate: activeCandidate, decisionId: createStableId(), key: createStableId() }); } }} onEvaluate={() => { if (!candidateWriteLocked) { setActionError(null); setEvaluationCandidateId(activeCandidate.candidateId); setEvaluationModal(true); } }} />{recovery?.kind === 'strategy-decision' ? <CommandRecovery kind="strategy-decision" identity={recovery.identity} onRecover={() => void recoverCommand()} busy={recoveryBusy} error={recovery.error} /> : null}</section> : null}
    {tab === 'evaluations' && selectedEvaluationId && evaluationDetail.data ? <section className="cp-panel strategy-detail-panel"><h3 ref={evaluationHeading} tabIndex={-1}>离线评测 {shortId(evaluationDetail.data.evaluationRunId)}</h3><EvaluationDetail evaluation={evaluationDetail.data} onReturn={() => { setSelectedCandidateId(evaluationDetail.data!.candidateIds[0] ?? null); setCandidateOverride(null); onTab('candidates'); }} /></section> : null}
     {runModal ? <Modal title="新建优化运行" onClose={() => { if (!busy) { suppressRunModalFocus.current = false; setRunModal(false); setActionError(null); } }} onUnmountFocus={(trigger) => { if (!suppressRunModalFocus.current) trigger?.focus(); }} busy={busy} locked={busy} onSubmit={createRun} submitLabel="提交优化运行">{actionError ? <ErrorBlock error={actionError} title="本次操作未保存" showRetry={false} focusOnMount={!busy} /> : null}<div className="strategy-form-grid"><Field label="策略资产"><select name="artifactId" value={runArtifactId || firstArtifactId} onChange={(e) => { const next = e.target.value; setRunArtifactId(next); if (next !== runArtifactId) setRunBaseVersionId(''); }}><option value="">选择服务端资产</option>{runArtifacts.data?.items.map((item) => <option key={item.artifactId} value={item.artifactId}>{item.displayName} · {shortId(item.artifactId)}</option>)}</select></Field><Field label="固定基线版本"><select name="baseVersionId" value={runBaseVersionId || firstVersionId} onChange={(e) => setRunBaseVersionId(e.target.value)}><option value="">选择不可变版本</option>{runVersions.data?.items.map((item) => <option key={item.versionId} value={item.versionId}>v{item.version} · {item.versionSummary}</option>)}</select></Field><Field label="适用模块"><select name="module" defaultValue="terms">{MODULES.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></Field><Field label="项目 ID（可选）"><input name="projectId" placeholder="不填表示全局" /></Field><Field label="开始时间（可选）"><input name="from" type="datetime-local" /></Field><Field label="结束时间（可选）"><input name="to" type="datetime-local" /></Field><Field label="最少证据数"><input name="minEvidenceCount" type="number" min="0" defaultValue="0" /></Field><Field label="最多事件数"><input name="maxEvents" type="number" min="1" max="100" defaultValue="100" /></Field><Field label="预算（CNY）"><input name="budgetCny" pattern="^(0|[1-9][0-9]{0,8})\\.[0-9]{6}$" defaultValue="0.000000" /></Field></div><p className="strategy-safe-copy">运行使用固定输入版本和确定性本地分析器；不调用 AI、网络或付费服务。</p></Modal> : null}
    {action ? <Modal title={action.kind === 'edit' ? '编辑学习候选' : action.kind === 'reject' ? '结构化驳回候选' : action.kind === 'restore' ? '恢复候选' : '送入离线评测'} onClose={() => { if (!busy) { setAction(null); setActionError(null); } }} busy={busy} locked={busy} onSubmit={submitDecision} submitLabel="保存决定">{actionError ? <ErrorBlock error={actionError} title="本次决定未保存" showRetry={false} focusOnMount={!busy} /> : null}<p className="strategy-safe-copy">候选 {shortId(action.candidate.candidateId)} · revision {action.candidate.revision}；本次只改变候选草稿，不会批准或发布。</p>{action.kind === 'edit' ? <div className="strategy-form-stack"><Field label="标题"><input name="title" required defaultValue={action.candidate.title} /></Field><Field label="理由"><textarea name="rationale" required defaultValue={action.candidate.rationale} /></Field><Field label="目标"><input name="target" required defaultValue={action.candidate.proposal.target} /></Field><Field label="建议值"><input name="value" required defaultValue={action.candidate.proposal.value} /></Field><Field label="备注"><textarea name="notes" defaultValue={action.candidate.proposal.notes} /></Field></div> : action.kind === 'reject' ? <div className="strategy-form-stack"><Field label="驳回原因"><select name="reason" defaultValue="证据不足"><option>证据不足</option><option>范围不符</option><option>风险过高</option></select></Field><Field label="补充说明"><textarea name="note" required minLength={2} /></Field></div> : <p>确认对当前候选执行“{action.kind === 'restore' ? '恢复为待审查' : '送入离线评测'}”。</p>}</Modal> : null}
    {evaluationModal ? <Modal title="创建离线评测" onClose={() => { if (!busy) { setEvaluationModal(false); setEvaluationCandidateId(null); setActionError(null); } }} busy={busy} locked={busy} onSubmit={createEvaluationRun} submitLabel="提交评测">{actionError ? <ErrorBlock error={actionError} title="本次评测未保存" showRetry={false} focusOnMount={!busy} /> : null}<p>候选 {shortId(evaluationCandidateId)} 将使用固定回归集评测；结果仅供人工判断，不会自动批准或发布。</p><Field label="预算（CNY）"><input name="budgetCny" defaultValue="0.000000" pattern="^(0|[1-9][0-9]{0,8})\\.[0-9]{6}$" /></Field></Modal> : null}
  </>;
};

const RunList = ({ data, selected, onSelect, page, setPage, status, setStatus }: { data: SystemControlOptimizationRunList | null; selected: string | null; onSelect: (id: string) => void; page: number; setPage: (n: number) => void; status: string; setStatus: (s: string) => void }) => <>
  <div className="strategy-filters"><label>运行状态<select aria-label="优化运行状态" value={status} onChange={(e) => { setStatus(e.target.value); setPage(0); }}><option value="">全部状态</option>{['queued', 'running', 'succeeded', 'failed', 'unknown'].map((s) => <option key={s} value={s}>{statusText[s]}</option>)}</select></label></div>
  {!data?.items.length ? <EmptyBlock title="暂无优化运行" detail="服务端尚未登记运行；可以显式创建一次零网络优化。" /> : <div className="strategy-table-wrap"><table><thead><tr><th>运行身份</th><th>状态</th><th>模块 / 项目 / 时间</th><th>固定基线版本</th><th>事件 / 候选</th><th>CNY 预算 / 实际</th><th>操作</th></tr></thead><tbody>{data.items.map((run) => <tr key={run.runId} aria-selected={selected === run.runId}><td><strong>{shortId(run.runId)}</strong><small>{formatDate(run.createdAt)}</small></td><td><span className={`strategy-status-chip status-${run.status}`}>{statusText[run.status]}</span></td><td>{run.module} / {shortId(run.projectId)}<small>{run.from ? formatDate(run.from) : '起始未知'} → {formatDate(run.to)}</small></td><td>{shortId(run.baseVersionId)}</td><td>{run.eventCount} / {run.candidateCount}</td><td>{run.budgetCny} / {run.actualCostCny ?? '待结算'}</td><td><button type="button" onClick={() => onSelect(run.runId)} aria-pressed={selected === run.runId}>查看运行</button></td></tr>)}</tbody></table></div>}
  {data ? <Pagination page={page} total={data.total} limit={data.limit} onPage={setPage} /> : null}
</>;

const CandidateList = ({ data, runs, selectedRunId, onRun, selected, onSelect, page, setPage }: { data: SystemControlStrategyCandidateList | null; runs: SystemControlOptimizationRunList | null; selectedRunId: string | null; onRun: (id: string) => void; selected: string | null; onSelect: (id: string) => void; page: number; setPage: (n: number) => void }) => <>
  <label className="strategy-inline-select">优化运行<select aria-label="候选所属优化运行" value={selectedRunId ?? ''} onChange={(e) => { onRun(e.target.value); setPage(0); }}><option value="">选择服务端运行</option>{runs?.items.map((run) => <option key={run.runId} value={run.runId}>{shortId(run.runId)} · {statusText[run.status]}</option>)}</select></label>
  {!selectedRunId ? <EmptyBlock title="请先选择优化运行" detail="候选只从已登记的服务端运行读取，不在浏览器生成。" /> : !data?.items.length ? <EmptyBlock title="暂无学习候选" detail="运行尚未产出候选，或当前筛选没有结果。" /> : <div className="strategy-table-wrap"><table><thead><tr><th>候选</th><th>状态</th><th>类型 / 模块</th><th>来源运行 / 固定版本</th><th>支持 / 反对 / 未知</th><th>修订</th><th>操作</th></tr></thead><tbody>{data.items.map((candidate) => <tr key={candidate.candidateId}><td><strong>{candidate.title}</strong><small>{shortId(candidate.candidateId)}</small></td><td>{statusText[candidate.status]}</td><td>{candidate.kind} / {candidate.module}</td><td><small>{shortId(candidate.runId)} / {shortId(candidate.baseVersionId)}</small></td><td>{candidate.supportCount} / {candidate.opposeCount} / {candidate.unknownCount}</td><td>{candidate.revision}</td><td><button type="button" onClick={() => onSelect(candidate.candidateId)}>查看候选</button></td></tr>)}</tbody></table></div>}
  {data ? <Pagination page={page} total={data.total} limit={data.limit} onPage={setPage} /> : null}
</>;

const CandidateDetail = ({ candidate, readOnly = false, onAction, onEvaluate }: { candidate: SystemControlStrategyCandidate; readOnly?: boolean; onAction: (kind: Action extends null ? never : Exclude<NonNullable<Action>['kind'], never>) => void; onEvaluate: () => void }) => <div className="strategy-detail-copy"><dl><div><dt>状态 / 模块</dt><dd>{statusText[candidate.status]} / {candidate.module}</dd></div><div><dt>来源运行 / 基线</dt><dd>{shortId(candidate.runId)} / {shortId(candidate.baseVersionId)}</dd></div><div><dt>理由</dt><dd>{candidate.rationale}</dd></div><div><dt>建议</dt><dd>{candidate.proposal.target} → {candidate.proposal.value}<br />{candidate.proposal.notes || '无备注'}</dd></div><div><dt>证据摘要</dt><dd><code>{candidate.evidenceDigest}</code> · 来源事件 {candidate.sourceEventRefId}</dd></div></dl><div className="cp-actions">{candidate.status === 'proposed' || candidate.status === 'edited' ? <><button className="cp-secondary" type="button" disabled={readOnly} onClick={() => onAction('edit')}>编辑建议</button><button className="cp-secondary" type="button" disabled={readOnly} onClick={() => onAction('reject')}>结构化驳回</button><button className="cp-primary" type="button" disabled={readOnly} onClick={() => onAction('send_to_evaluation')}>送入离线评测</button></> : null}{candidate.status === 'rejected' ? <button className="cp-secondary" type="button" disabled={readOnly} onClick={() => onAction('restore')}>恢复候选</button> : null}{candidate.status === 'evaluation_ready' ? <button className="cp-primary" type="button" disabled={readOnly} onClick={onEvaluate}>创建离线评测</button> : null}</div></div>;

const RunDetail = ({ run, onReload }: { run: SystemControlOptimizationRun; onReload: () => void }) => <div className="strategy-detail-copy"><dl><div><dt>状态 / 分析器</dt><dd>{statusText[run.status]} / {run.analyzerKey}</dd></div><div><dt>固定输入</dt><dd>资产 {shortId(run.artifactId)} · 版本 {shortId(run.baseVersionId)}</dd></div><div><dt>事件 / 候选</dt><dd>{run.eventCount} / {run.candidateCount}</dd></div><div><dt>成本</dt><dd>{run.budgetCny} CNY / {run.actualCostCny ?? '待结算'}</dd></div><div><dt>请求身份</dt><dd><code>{run.requestId}</code></dd></div></dl>{run.status === 'failed' ? <button className="cp-secondary" type="button" onClick={onReload}>读取失败事实</button> : null}</div>;

const EvaluationList = ({ data, selected, onSelect, page, setPage, status, setStatus }: { data: SystemControlEvaluationRunList | null; selected: string | null; onSelect: (id: string) => void; page: number; setPage: (n: number) => void; status: string; setStatus: (s: string) => void }) => <><div className="strategy-filters"><label>评测状态<select aria-label="离线评测状态" value={status} onChange={(e) => { setStatus(e.target.value); setPage(0); }}><option value="">全部状态</option>{['queued', 'running', 'succeeded', 'failed', 'unknown'].map((s) => <option key={s} value={s}>{statusText[s]}</option>)}</select></label></div>{!data?.items.length ? <EmptyBlock title="暂无离线评测" detail="候选送入评测后，服务端会提供确定性指标。" /> : <div className="strategy-table-wrap"><table><thead><tr><th>评测身份</th><th>状态</th><th>候选数</th><th>预算 / 实际</th><th>操作</th></tr></thead><tbody>{data.items.map((item) => <tr key={item.evaluationRunId}><td><strong>{shortId(item.evaluationRunId)}</strong><small>{formatDate(item.createdAt)}</small></td><td>{statusText[item.status]}</td><td>{item.candidateIds.length}</td><td>{item.budgetCny} / {item.actualCostCny ?? '待结算'} CNY</td><td><button type="button" onClick={() => onSelect(item.evaluationRunId)} aria-pressed={selected === item.evaluationRunId}>查看评测</button></td></tr>)}</tbody></table></div>}{data ? <Pagination page={page} total={data.total} limit={data.limit} onPage={setPage} /> : null}</>;
const EvaluationDetail = ({ evaluation, onReturn }: { evaluation: SystemControlEvaluationRun; onReturn: () => void }) => <div className="strategy-detail-copy"><dl><div><dt>状态 / 请求</dt><dd>{statusText[evaluation.status]} / <code>{evaluation.requestId}</code></dd></div><div><dt>候选摘要</dt><dd><code>{evaluation.candidateDigest}</code></dd></div><div><dt>成本</dt><dd>{evaluation.actualCostCny ?? '待结算'} CNY</dd></div></dl>{evaluation.metrics ? <div className="strategy-evaluation-grid"><div><strong>人工复核数</strong><span>{evaluation.metrics.baselineManualReviewCount} → {evaluation.metrics.candidateManualReviewCount}</span></div><div><strong>误报估计</strong><span>{evaluation.metrics.estimatedFalsePositiveCount}</span></div><div><strong>漏报估计</strong><span>{evaluation.metrics.estimatedFalseNegativeCount}</span></div><div><strong>处理秒数</strong><span>{evaluation.metrics.baselineHandlingSeconds} → {evaluation.metrics.candidateHandlingSeconds}</span></div></div> : <p className="strategy-safe-copy">评测指标尚未形成；不会显示百分比或推算结果。</p>}<p className="strategy-safe-copy">指标仅供人工判断，不会自动批准、发布或改变生产规则。</p><div className="cp-actions"><button className="cp-secondary" type="button" onClick={onReturn}>返回候选</button></div></div>;
const Pagination = ({ page, total, limit, onPage }: { page: number; total: number; limit: number; onPage: (page: number) => void }) => <div className="strategy-pagination"><span>第 {total ? page + 1 : 0} / {Math.ceil(total / limit) || 0} 页</span><div><button className="cp-secondary" type="button" disabled={page === 0} onClick={() => onPage(page - 1)}>上一页</button><button className="cp-secondary" type="button" disabled={(page + 1) * limit >= total} onClick={() => onPage(page + 1)}>下一页</button></div></div>;
