import {
  AcceptanceCommandResultSchema, AcceptanceEditEventListSchema, AcceptanceEpisodeCommandResultSchema,
  AcceptanceEpisodeDetailSchema, AcceptancePlaybackGrantSchema, AcceptancePreflightSchema,
  AcceptanceReleaseCommandResultSchema, AcceptanceReleaseListSchema, AcceptanceReworkCommandResultSchema,
  AcceptanceReworkListSchema, AcceptanceSessionDetailSchema, AcceptanceSessionListSchema,
  ApiErrorSchema, ApplyAcceptanceCueCommandBodySchema, CreateAcceptanceIssueBodySchema,
  CreateAcceptancePlaybackGrantBodySchema, CreateAcceptanceReleaseBodySchema, CreateAcceptanceReworkBodySchema,
  CreateAcceptanceSessionBodySchema, PassAcceptanceEpisodeBodySchema, PassAcceptanceEpisodesBodySchema,
  PassAcceptanceEpisodesResultSchema, RedoAcceptanceEditBodySchema, ResolveAcceptanceIssueBodySchema,
  SelectAcceptanceVideoBodySchema, UndoAcceptanceEditBodySchema,
} from '@qimao-terms-cloud/contracts';
import type { FastifyPluginAsyncTypebox } from '@fastify/type-provider-typebox';
import { Type } from '@sinclair/typebox';
import type { FastifyReply } from 'fastify';

import { SubtitleAcceptanceError } from './subtitle-acceptance.errors.js';
import { SubtitleAcceptanceService } from './subtitle-acceptance.service.js';

const Project = Type.Object({ projectId: Type.String({ format: 'uuid' }) });
const Session = Type.Object({ projectId: Type.String({ format: 'uuid' }), sessionId: Type.String({ format: 'uuid' }) });
const Episode = Type.Object({ projectId: Type.String({ format: 'uuid' }), sessionId: Type.String({ format: 'uuid' }), episodeNumber: Type.String({ pattern: '^(?:[1-9]|[1-9][0-9]|100)$' }) });
const Issue = Type.Object({ projectId: Type.String({ format: 'uuid' }), sessionId: Type.String({ format: 'uuid' }), episodeNumber: Type.String({ pattern: '^(?:[1-9]|[1-9][0-9]|100)$' }), issueId: Type.String({ format: 'uuid' }) });
const Playback = Type.Object({ token: Type.String({ minLength: 20, maxLength: 200 }) });
const Idempotency = Type.Object({ 'idempotency-key': Type.String({ minLength: 8, maxLength: 200 }) });

const sendError = (reply: FastifyReply, requestId: string, error: SubtitleAcceptanceError) => reply.code(error.statusCode).send({ error: { code: error.code, message: error.message, retryable: error.retryable, action: error.action, requestId } });

export const subtitleAcceptanceRoutes: FastifyPluginAsyncTypebox = async (app) => {
  const service = new SubtitleAcceptanceService(app.database, app.uploadStorage);
  const handle = async <T>(reply: FastifyReply, requestId: string, operation: () => Promise<T>) => {
    try { return await operation(); }
    catch (error) { if (error instanceof SubtitleAcceptanceError) return sendError(reply, requestId, error); app.log.error({ err: error, requestId }, 'subtitle acceptance request failed'); throw error; }
  };

  app.post('/api/projects/:projectId/subtitle-acceptance/sessions', { schema: { params: Project, headers: Idempotency, body: CreateAcceptanceSessionBodySchema, response: { 200: AcceptanceCommandResultSchema, 201: AcceptanceCommandResultSchema, 404: ApiErrorSchema, 409: ApiErrorSchema, 422: ApiErrorSchema } } }, async (request, reply) => handle(reply, request.id, async () => { const result = await service.createSession(request.params.projectId, request.body, request.headers['idempotency-key']); return reply.code(result.replay ? 200 : 201).send(result); }));
  app.get('/api/projects/:projectId/subtitle-acceptance/sessions', { schema: { params: Project, response: { 200: AcceptanceSessionListSchema } } }, async (request) => service.listSessions(request.params.projectId));
  app.get('/api/projects/:projectId/subtitle-acceptance/sessions/:sessionId', { schema: { params: Session, response: { 200: AcceptanceSessionDetailSchema, 404: ApiErrorSchema } } }, async (request, reply) => handle(reply, request.id, () => service.getSession(request.params.projectId, request.params.sessionId)));
  app.get('/api/projects/:projectId/subtitle-acceptance/sessions/:sessionId/episodes/:episodeNumber', { schema: { params: Episode, response: { 200: AcceptanceEpisodeDetailSchema, 404: ApiErrorSchema } } }, async (request, reply) => handle(reply, request.id, () => service.getEpisode(request.params.projectId, request.params.sessionId, Number(request.params.episodeNumber))));
  app.get('/api/projects/:projectId/subtitle-acceptance/sessions/:sessionId/episodes/:episodeNumber/events', { schema: { params: Episode, response: { 200: AcceptanceEditEventListSchema } } }, async (request, reply) => handle(reply, request.id, () => service.events(request.params.projectId, request.params.sessionId, Number(request.params.episodeNumber))));

  app.post('/api/projects/:projectId/subtitle-acceptance/sessions/:sessionId/episodes/:episodeNumber/cues', { schema: { params: Episode, headers: Idempotency, body: ApplyAcceptanceCueCommandBodySchema, response: { 200: AcceptanceEpisodeCommandResultSchema, 201: AcceptanceEpisodeCommandResultSchema, 409: ApiErrorSchema, 422: ApiErrorSchema } } }, async (request, reply) => handle(reply, request.id, async () => { const result = await service.edit(request.params.projectId, request.params.sessionId, Number(request.params.episodeNumber), request.body, request.headers['idempotency-key']); return reply.code(result.replay ? 200 : 201).send(result); }));
  for (const [direction, schema] of [['undo', UndoAcceptanceEditBodySchema], ['redo', RedoAcceptanceEditBodySchema]] as const) app.post(`/api/projects/:projectId/subtitle-acceptance/sessions/:sessionId/episodes/:episodeNumber/${direction}`, { schema: { params: Episode, headers: Idempotency, body: schema, response: { 200: AcceptanceEpisodeCommandResultSchema, 201: AcceptanceEpisodeCommandResultSchema, 409: ApiErrorSchema, 422: ApiErrorSchema } } }, async (request, reply) => handle(reply, request.id, async () => { const result = await service.restore(request.params.projectId, request.params.sessionId, Number(request.params.episodeNumber), request.body, request.headers['idempotency-key'], direction); return reply.code(result.replay ? 200 : 201).send(result); }));
  app.post('/api/projects/:projectId/subtitle-acceptance/sessions/:sessionId/episodes/:episodeNumber/issues', { schema: { params: Episode, headers: Idempotency, body: CreateAcceptanceIssueBodySchema, response: { 200: AcceptanceEpisodeCommandResultSchema, 201: AcceptanceEpisodeCommandResultSchema } } }, async (request, reply) => handle(reply, request.id, async () => { const result = await service.createIssue(request.params.projectId, request.params.sessionId, Number(request.params.episodeNumber), request.body, request.headers['idempotency-key']); return reply.code(result.replay ? 200 : 201).send(result); }));
  app.patch('/api/projects/:projectId/subtitle-acceptance/sessions/:sessionId/episodes/:episodeNumber/issues/:issueId', { schema: { params: Issue, headers: Idempotency, body: ResolveAcceptanceIssueBodySchema, response: { 200: AcceptanceEpisodeCommandResultSchema } } }, async (request, reply) => handle(reply, request.id, () => service.resolveIssue(request.params.projectId, request.params.sessionId, Number(request.params.episodeNumber), request.params.issueId, request.body, request.headers['idempotency-key'])));
  app.post('/api/projects/:projectId/subtitle-acceptance/sessions/:sessionId/episodes/:episodeNumber/video', { schema: { params: Episode, headers: Idempotency, body: SelectAcceptanceVideoBodySchema, response: { 200: AcceptanceEpisodeCommandResultSchema, 201: AcceptanceEpisodeCommandResultSchema } } }, async (request, reply) => handle(reply, request.id, async () => { const result = await service.selectVideo(request.params.projectId, request.params.sessionId, Number(request.params.episodeNumber), request.body, request.headers['idempotency-key']); return reply.code(result.replay ? 200 : 201).send(result); }));
  app.get('/api/projects/:projectId/subtitle-acceptance/sessions/:sessionId/preflight', { schema: { params: Session, response: { 200: AcceptancePreflightSchema } } }, async (request, reply) => handle(reply, request.id, () => service.preflight(request.params.projectId, request.params.sessionId)));
  app.post('/api/projects/:projectId/subtitle-acceptance/sessions/:sessionId/episodes/:episodeNumber/pass', { schema: { params: Episode, headers: Idempotency, body: PassAcceptanceEpisodeBodySchema, response: { 200: PassAcceptanceEpisodesResultSchema, 201: PassAcceptanceEpisodesResultSchema } } }, async (request, reply) => handle(reply, request.id, async () => { const result = await service.passOne(request.params.projectId, request.params.sessionId, Number(request.params.episodeNumber), request.body, request.headers['idempotency-key']); return reply.code(result.replay ? 200 : 201).send(result); }));
  app.post('/api/projects/:projectId/subtitle-acceptance/sessions/:sessionId/pass-eligible', { schema: { params: Session, headers: Idempotency, body: PassAcceptanceEpisodesBodySchema, response: { 200: PassAcceptanceEpisodesResultSchema, 201: PassAcceptanceEpisodesResultSchema } } }, async (request, reply) => handle(reply, request.id, async () => { const result = await service.passEligible(request.params.projectId, request.params.sessionId, request.body, request.headers['idempotency-key']); return reply.code(result.replay ? 200 : 201).send(result); }));
  app.post('/api/projects/:projectId/subtitle-acceptance/sessions/:sessionId/rework', { schema: { params: Session, headers: Idempotency, body: CreateAcceptanceReworkBodySchema, response: { 200: AcceptanceReworkCommandResultSchema, 201: AcceptanceReworkCommandResultSchema } } }, async (request, reply) => handle(reply, request.id, async () => { const result = await service.createRework(request.params.projectId, request.params.sessionId, request.body, request.headers['idempotency-key']); return reply.code(result.replay ? 200 : 201).send(result); }));
  app.get('/api/projects/:projectId/subtitle-acceptance/sessions/:sessionId/rework', { schema: { params: Session, response: { 200: AcceptanceReworkListSchema } } }, async (request, reply) => handle(reply, request.id, () => service.rework(request.params.projectId, request.params.sessionId)));
  app.post('/api/projects/:projectId/subtitle-acceptance/sessions/:sessionId/releases', { schema: { params: Session, headers: Idempotency, body: CreateAcceptanceReleaseBodySchema, response: { 200: AcceptanceReleaseCommandResultSchema, 201: AcceptanceReleaseCommandResultSchema } } }, async (request, reply) => handle(reply, request.id, async () => { const result = await service.createRelease(request.params.projectId, request.params.sessionId, request.body, request.headers['idempotency-key']); return reply.code(result.replay ? 200 : 201).send(result); }));
  app.get('/api/projects/:projectId/subtitle-acceptance/releases', { schema: { params: Project, response: { 200: AcceptanceReleaseListSchema } } }, async (request) => service.listReleases(request.params.projectId));
  app.post('/api/projects/:projectId/subtitle-acceptance/sessions/:sessionId/episodes/:episodeNumber/playback', { schema: { params: Episode, body: CreateAcceptancePlaybackGrantBodySchema, response: { 201: AcceptancePlaybackGrantSchema } } }, async (request, reply) => handle(reply, request.id, async () => reply.code(201).send(await service.createPlaybackGrant(request.params.projectId, request.params.sessionId, Number(request.params.episodeNumber), request.body))));
  app.get('/api/subtitle-acceptance/playback/:token', { schema: { params: Playback } }, async (request, reply) => handle(reply, request.id, async () => reply.type('application/octet-stream').send(Buffer.from(await service.playback(request.params.token)))));
};
