import { createHash, randomUUID } from 'node:crypto';
import type { PoolClient } from 'pg';
import type { DatabasePool } from '../../database/pool.js';
import type { SystemControlPrincipal } from './system-control.auth.js';
import { alignEpisode, effectiveSystemDecision, scanFormatIssues, type AlignmentCue } from '../pre-review/pre-review.domain.js';
import type {
  SystemControlPreReviewRulePack, SystemControlStrategyBaselinePreview, SystemControlStrategyHistory as SystemControlHistory,
  SystemControlStrategyHistoryQuery, SystemControlStrategyImpactRun, SystemControlStrategyRuntimeTarget,
  SystemControlStrategyRuntimeVersion, SystemControlStrategyReleaseCommand,
} from '@qimao-terms-cloud/contracts';

export class SystemControlStrategyRuntimeError extends Error {
  constructor(readonly code: string, message: string, readonly statusCode: 400 | 404 | 409 | 422 = 400) { super(message); this.name = 'SystemControlStrategyRuntimeError'; }
}

const MODULE = 'pre_review';
const BASELINE_RULE_PACK: SystemControlPreReviewRulePack = {
  payloadType: 'pre_review_local_rule_pack_v1', alignmentNearbyGapMs: 350, alignmentSimilarityThreshold: 0.75,
  maxCharacters: 28, forbidSentencePunctuation: true, forbidMarkup: true, forbidBrackets: true, requireSpeakerDashForMultipleLines: true,
};
const stable = (value: unknown): unknown => Array.isArray(value) ? value.map(stable) : value && typeof value === 'object' ? Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([k, v]) => [k, stable(v)])) : value;
const digest = (value: unknown) => createHash('sha256').update(JSON.stringify(stable(value))).digest('hex');
const isUuid = (value: string) => /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const iso = (value: Date | string) => new Date(value).toISOString();
const hasAtMostSixDecimalPlaces = (value: unknown) => typeof value === 'number' && Number.isFinite(value)
  && Math.abs(value * 1_000_000 - Math.round(value * 1_000_000)) <= 1e-9;
const commandConflict = (code: string, message: string) => new SystemControlStrategyRuntimeError(code, message, 409);
const parsePage = (query: SystemControlStrategyHistoryQuery) => {
  const limit = query.limit === undefined ? 50 : Number(query.limit); const offset = query.offset === undefined ? 0 : Number(query.offset);
  if (!Number.isInteger(limit) || limit < 1 || limit > 100 || !Number.isInteger(offset) || offset < 0 || offset > 1_000_000) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_INVALID_PAGE', '分页参数无效', 400);
  return { limit, offset };
};
const asRulePack = (value: unknown): SystemControlPreReviewRulePack => {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_INVALID_RULE_PACK', '规则包无效', 422);
  const p = value as Record<string, unknown>;
  const keys = Object.keys(BASELINE_RULE_PACK).sort();
  if (JSON.stringify(Object.keys(p).sort()) !== JSON.stringify(keys) || p.payloadType !== 'pre_review_local_rule_pack_v1' || !Number.isInteger(p.alignmentNearbyGapMs) || Number(p.alignmentNearbyGapMs) < 0 || Number(p.alignmentNearbyGapMs) > 5000 || !Number.isInteger(p.maxCharacters) || Number(p.maxCharacters) < 1 || Number(p.maxCharacters) > 200 || !hasAtMostSixDecimalPlaces(p.alignmentSimilarityThreshold) || Number(p.alignmentSimilarityThreshold) < 0 || Number(p.alignmentSimilarityThreshold) > 1 || [p.forbidSentencePunctuation, p.forbidMarkup, p.forbidBrackets, p.requireSpeakerDashForMultipleLines].some((v) => typeof v !== 'boolean')) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_INVALID_RULE_PACK', '规则包无效', 422);
  return p as SystemControlPreReviewRulePack;
};
type RuntimeInvariantResults = { oneToOne: 'pass' | 'fail' | 'unknown'; asrQuality: 'pass' | 'fail' | 'unknown'; blockingFormat: 'pass' | 'fail' | 'unknown'; termConflicts: 'pass' | 'fail' | 'unknown' };
type RuntimeEvaluation = { blockers: string[]; invariants: RuntimeInvariantResults; affectedSessionCount: number; sampleCount: number };
const toVersion = (row: any): SystemControlStrategyRuntimeVersion => ({ strategyVersionId: row.id, module: MODULE, origin: row.origin, status: row.runtime_status, contentDigest: row.content_digest, baseVersionId: row.base_version_id ?? null, source: row.source ?? 'manual', evaluationRunId: row.evaluation_run_id ?? null, candidateDigest: row.candidate_digest ?? null, rulePack: asRulePack(row.payload), createdAt: iso(row.created_at), updatedAt: iso(row.runtime_updated_at ?? row.created_at) });

export class SystemControlStrategyRuntimeService {
  private readonly evaluator: (snapshot: any) => RuntimeEvaluation;
  constructor(private readonly database: DatabasePool, options: { evaluator?: (snapshot: any) => RuntimeEvaluation } = {}) {
    this.evaluator = options.evaluator ?? ((snapshot) => this.evaluateSnapshot(snapshot));
  }
  private async lock(client: PoolClient, stableId: string) { await client.query('SELECT pg_advisory_xact_lock(hashtext($1))', [`strategy-command:${stableId}`]); }
  private async audit(client: PoolClient, input: { principal: SystemControlPrincipal; requestId: string }, action: string, resourceId: string, key: string, snapshot: unknown) {
    await client.query(`INSERT INTO system_control_audit_events(actor_subject,actor_audience,action,resource_type,resource_id,idempotency_key,request_id,result,after_snapshot) VALUES($1,$2,$3,'strategy_runtime',$4,$5,$6,'succeeded',$7)`, [input.principal.subject, Array.isArray(input.principal.audience) ? input.principal.audience.join(',') : input.principal.audience, action, resourceId, key, input.requestId, snapshot]);
  }
  private async command(client: PoolClient, id: string, kind: string, key: string, hash: string, resourceId: string, snapshot: unknown) {
    await client.query('INSERT INTO system_control_commands(id,command_kind,idempotency_key,stable_command_key,request_hash,resource_id,response_snapshot) VALUES($1,$2,$3,$4,$5,$6,$7)', [id, kind, key, id, hash, resourceId, snapshot]);
  }
  async getTarget(): Promise<SystemControlStrategyRuntimeTarget> {
    const r = await this.database.query(`SELECT v.id,v.content_digest,v.payload,v.created_at,v.runtime_updated_at,v.base_version_id,v.source,v.evaluation_run_id,v.candidate_digest,a.origin,v.runtime_status FROM strategy_runtime_active_pointers p JOIN strategy_artifact_versions v ON v.id=p.strategy_version_id JOIN strategy_artifacts a ON a.id=v.artifact_id WHERE p.module=$1`, [MODULE]);
    return { module: MODULE, active: r.rows[0] ? toVersion(r.rows[0]) : null };
  }
  async getVersion(strategyVersionId: string): Promise<SystemControlStrategyRuntimeVersion> {
    const r = await this.database.query(`SELECT v.id,v.content_digest,v.payload,v.created_at,v.runtime_updated_at,v.base_version_id,v.source,v.evaluation_run_id,v.candidate_digest,a.origin,a.runtime_module,v.runtime_status
      FROM strategy_artifact_versions v JOIN strategy_artifacts a ON a.id=v.artifact_id
      WHERE v.id=$1 AND a.runtime_module=$2`, [strategyVersionId, MODULE]);
    if (!r.rows[0]) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_VERSION_NOT_FOUND', '策略版本不存在', 404);
    return toVersion(r.rows[0]);
  }
  async getBaselinePreview(): Promise<SystemControlStrategyBaselinePreview> {
    const r = await this.database.query(`SELECT v.id,v.content_digest,v.payload FROM strategy_artifacts a JOIN strategy_artifact_versions v ON v.artifact_id=a.id WHERE a.origin='system_baseline' AND a.runtime_module=$1 ORDER BY v.created_at ASC,v.id ASC LIMIT 1`, [MODULE]);
    return { module: MODULE, origin: 'system_baseline', contentDigest: r.rows[0]?.content_digest ?? digest(BASELINE_RULE_PACK), rulePack: r.rows[0] ? asRulePack(r.rows[0].payload) : BASELINE_RULE_PACK, imported: Boolean(r.rows[0]), strategyVersionId: r.rows[0]?.id ?? null };
  }
  async getBaselineImport(id: string) { return this.getCommandVersion(id, 'strategy_runtime_baseline_import', 'SYSTEM_CONTROL_STRATEGY_BASELINE_IMPORT_NOT_FOUND', '基线导入命令不存在'); }
  private async getCommandVersion(id: string, kind: string, code: string, message: string): Promise<SystemControlStrategyRuntimeVersion> { const r = await this.database.query<{ response_snapshot: SystemControlStrategyRuntimeVersion }>('SELECT response_snapshot FROM system_control_commands WHERE id=$1 AND command_kind=$2', [id, kind]); if (!r.rows[0]) throw new SystemControlStrategyRuntimeError(code, message, 404); return r.rows[0].response_snapshot; }

  async importBaseline(input: { baselineImportId: string; artifactId: string; versionId: string; idempotencyKey: string; requestId: string; principal: SystemControlPrincipal }) {
    if (![input.baselineImportId, input.artifactId, input.versionId].every(isUuid) || input.idempotencyKey.trim().length < 8) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_INVALID_COMMAND', '导入命令身份无效', 422);
    const requestHash = digest({ path: '/strategy/runtime-targets/pre_review/baseline-imports', baselineImportId: input.baselineImportId, artifactId: input.artifactId, versionId: input.versionId, payload: BASELINE_RULE_PACK }); const client = await this.database.connect();
    try {
      await client.query('BEGIN'); await this.lock(client, input.baselineImportId); await this.lock(client, input.idempotencyKey);
      const stableRow = await client.query<{ request_hash: string; response_snapshot: SystemControlStrategyRuntimeVersion }>('SELECT request_hash,response_snapshot FROM system_control_commands WHERE stable_command_key=$1 FOR UPDATE', [input.baselineImportId]);
      if (stableRow.rows[0]) { if (stableRow.rows[0].request_hash !== requestHash) throw commandConflict('SYSTEM_CONTROL_STRATEGY_BASELINE_ID_REUSED', '基线导入身份已被其他请求使用'); await client.query('COMMIT'); return { version: stableRow.rows[0].response_snapshot, replay: true }; }
      const keyRow = await client.query<{ request_hash: string; response_snapshot: SystemControlStrategyRuntimeVersion }>('SELECT request_hash,response_snapshot FROM system_control_commands WHERE command_kind=$1 AND idempotency_key=$2 FOR UPDATE', ['strategy_runtime_baseline_import', input.idempotencyKey]);
      if (keyRow.rows[0]) { if (keyRow.rows[0].request_hash !== requestHash) throw commandConflict('SYSTEM_CONTROL_STRATEGY_IDEMPOTENCY_KEY_REUSED', '幂等键已被其他请求使用'); await client.query('COMMIT'); return { version: keyRow.rows[0].response_snapshot, replay: true }; }
      const existing = await client.query(`SELECT v.id,v.content_digest,v.payload,v.created_at,v.runtime_updated_at,v.base_version_id,v.source,v.evaluation_run_id,v.candidate_digest,a.origin,v.runtime_status FROM strategy_artifacts a JOIN strategy_artifact_versions v ON v.artifact_id=a.id WHERE a.origin='system_baseline' AND a.runtime_module=$1 ORDER BY v.created_at ASC,v.id ASC LIMIT 1 FOR UPDATE`, [MODULE]);
      let version: SystemControlStrategyRuntimeVersion;
      if (existing.rows[0]) version = toVersion(existing.rows[0]);
      else {
        await client.query(`INSERT INTO strategy_artifacts(id,artifact_kind,display_name,purpose,applicable_modules,status,created_by,origin,protected,runtime_module) VALUES($1,'local_rule_pack','系统基线','前置审改本地规则基线',ARRAY['pre_review'],'draft',$2,'system_baseline',true,'pre_review')`, [input.artifactId, input.principal.subject]);
        const inserted = await client.query(`INSERT INTO strategy_artifact_versions(id,artifact_id,version,schema_version,payload,content_digest,created_by,source,runtime_status) VALUES($1,$2,1,1,$3,$4,$5,'system_baseline','draft') RETURNING id,content_digest,payload,created_at,runtime_status,runtime_updated_at,base_version_id,source,evaluation_run_id,candidate_digest`, [input.versionId, input.artifactId, BASELINE_RULE_PACK, digest(BASELINE_RULE_PACK), input.principal.subject]);
        version = toVersion({ ...inserted.rows[0], origin: 'system_baseline' });
      }
      await this.command(client, input.baselineImportId, 'strategy_runtime_baseline_import', input.idempotencyKey, requestHash, version.strategyVersionId, version); await this.audit(client, input, 'strategy_runtime_baseline_import', version.strategyVersionId, input.idempotencyKey, { origin: 'system_baseline', contentDigest: version.contentDigest }); await client.query('COMMIT'); return { version, replay: false };
    } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); }
  }

  async createImpact(input: { impactRunId: string; strategyVersionId: string; idempotencyKey: string; requestId: string; principal: SystemControlPrincipal }) {
    if (![input.impactRunId, input.strategyVersionId].every(isUuid) || input.idempotencyKey.trim().length < 8) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_INVALID_COMMAND', '影响检查命令身份无效', 422);
    const requestHash = digest({ impactRunId: input.impactRunId, strategyVersionId: input.strategyVersionId }); const client = await this.database.connect();
    try {
      await client.query('BEGIN'); await this.lock(client, input.impactRunId); await this.lock(client, input.idempotencyKey);
      const stableRow = await client.query<{ request_hash: string; response_snapshot: SystemControlStrategyImpactRun }>('SELECT request_hash,response_snapshot FROM system_control_commands WHERE stable_command_key=$1 FOR UPDATE', [input.impactRunId]); if (stableRow.rows[0]) { if (stableRow.rows[0].request_hash !== requestHash) throw commandConflict('SYSTEM_CONTROL_STRATEGY_IMPACT_ID_REUSED', '影响检查身份已被其他请求使用'); await client.query('COMMIT'); return { run: stableRow.rows[0].response_snapshot, replay: true }; }
      const version = await client.query(`SELECT v.id,v.content_digest,v.payload,v.runtime_status,a.runtime_module FROM strategy_artifact_versions v JOIN strategy_artifacts a ON a.id=v.artifact_id WHERE v.id=$1 FOR SHARE`, [input.strategyVersionId]); if (!version.rows[0] || version.rows[0].runtime_module !== MODULE) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_VERSION_NOT_FOUND', '策略版本不存在', 404);
      const candidatePack = asRulePack(version.rows[0].payload);
      const blocker = await client.query<{ count: string }>(`SELECT count(*)::text FROM pre_edit_sessions WHERE strategy_version_id IS NULL AND status IN ('preparing','ready','limited')`); const oldCount = Number(blocker.rows[0]?.count ?? 0); const blockers = oldCount ? ['存在尚未绑定策略版本的旧前置审改会话'] : [];
      const samples = await client.query<any>(`SELECT item.id AS item_id,item.session_id,item.episode_id,item.group_id,item.current_text,item.term_evidence,episode.asr_quality_status,episode.video_duration_ms::text,
          COALESCE((SELECT jsonb_agg(jsonb_build_object('cueId',cue.id,'cueIndex',cue.cue_index,'startMs',cue.start_ms,'endMs',cue.end_ms,'text',cue.text,'confidence',NULL) ORDER BY cue.cue_index,cue.id) FROM term_cues cue WHERE cue.id=ANY(group_row.company_cue_ids)),'[]'::jsonb) AS company_cues,
          COALESCE((SELECT jsonb_agg(jsonb_build_object('cueId',cue.id,'cueIndex',cue.cue_index,'startMs',cue.start_ms,'endMs',cue.end_ms,'text',cue.text,'confidence',cue.confidence) ORDER BY cue.cue_index,cue.id) FROM asr_cues cue WHERE cue.id=ANY(group_row.asr_cue_ids)),'[]'::jsonb) AS asr_cues
        FROM pre_edit_items item JOIN pre_edit_sessions session ON session.id=item.session_id JOIN pre_edit_episodes episode ON episode.id=item.episode_id JOIN pre_edit_alignment_groups group_row ON group_row.id=item.group_id
        WHERE session.strategy_version_id IS NOT NULL ORDER BY item.id LIMIT 100`);
      const current = await client.query(`SELECT p.strategy_version_id,v.content_digest,v.payload FROM strategy_runtime_active_pointers p JOIN strategy_artifact_versions v ON v.id=p.strategy_version_id WHERE p.module=$1`, [MODULE]);
      const currentPack = current.rows[0] ? asRulePack(current.rows[0].payload) : null;
      const fields = ['alignmentNearbyGapMs', 'alignmentSimilarityThreshold', 'maxCharacters', 'forbidSentencePunctuation', 'forbidMarkup', 'forbidBrackets', 'requireSpeakerDashForMultipleLines'];
      const fieldDifferences: unknown[] = fields.filter((field) => !currentPack || JSON.stringify((currentPack as any)[field]) !== JSON.stringify((candidatePack as any)[field])).map((field) => ({ field, current: currentPack ? (currentPack as any)[field] : null, candidate: (candidatePack as any)[field] }));
      const sampleInputs = samples.rows.map((row: any) => ({ itemId: row.item_id, sessionId: row.session_id, episodeId: row.episode_id, groupId: row.group_id, currentText: row.current_text ?? null, termEvidence: row.term_evidence ?? [], asrQualityStatus: row.asr_quality_status ?? null, videoDurationMs: row.video_duration_ms === null ? null : Number(row.video_duration_ms), companyCues: row.company_cues ?? [], asrCues: row.asr_cues ?? [] }));
      const coverage = { source: 'pre_edit_items', bounded: true, currentStrategyVersionId: current.rows[0]?.strategy_version_id ?? null, currentContentDigest: current.rows[0]?.content_digest ?? null, sampleRefs: sampleInputs.map((row: any) => ({ itemId: row.itemId, sessionId: row.sessionId, episodeId: row.episodeId })) };
      const invariantResults = { oneToOne: 'unknown', asrQuality: 'unknown', blockingFormat: 'unknown', termConflicts: 'unknown' };
      const snapshotId = input.impactRunId;
      const snapshotInput = { snapshotId, strategyVersionId: input.strategyVersionId, contentDigest: version.rows[0].content_digest, candidateRulePack: candidatePack, currentStrategyVersionId: current.rows[0]?.strategy_version_id ?? null, currentContentDigest: current.rows[0]?.content_digest ?? null, currentRulePack: currentPack, oldUnboundSessionCount: oldCount, blockers, fieldDifferences, samples: sampleInputs };
      const snapshotDigest = digest(snapshotInput);
      const sampleSessionCount = new Set(sampleInputs.map((sample: any) => sample.sessionId)).size;
      const row = await client.query(`INSERT INTO strategy_runtime_impact_runs(id,strategy_version_id,status,snapshot_id,snapshot_digest,snapshot_input,content_digest,coverage,blockers,invariant_results,field_differences,affected_session_count,sample_count,old_unbound_session_count,request_id,created_by) VALUES($1,$2,'queued',$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`, [input.impactRunId, input.strategyVersionId, snapshotId, snapshotDigest, JSON.stringify(snapshotInput), version.rows[0].content_digest, JSON.stringify(coverage), JSON.stringify(blockers), JSON.stringify(invariantResults), JSON.stringify(fieldDifferences), sampleSessionCount, sampleInputs.length, oldCount, input.requestId, input.principal.subject]);
      const queued = this.toImpact(row.rows[0]); await this.command(client, input.impactRunId, 'strategy_runtime_impact', input.idempotencyKey, requestHash, input.strategyVersionId, queued); await this.audit(client, input, 'strategy_runtime_impact_queued', input.strategyVersionId, input.idempotencyKey, { status: queued.status, snapshotDigest }); await client.query('COMMIT');
      return { run: queued, replay: false };
    } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); }
  }
  private toImpact(row: any): SystemControlStrategyImpactRun { return { impactRunId: row.id, strategyVersionId: row.strategy_version_id, status: row.status, snapshotId: row.snapshot_id ?? row.id, blockers: Array.isArray(row.blockers) ? row.blockers : [], oldUnboundSessionCount: Number(row.old_unbound_session_count), affectedSessionCount: Number(row.affected_session_count ?? row.old_unbound_session_count), sampleCount: Number(row.sample_count ?? row.old_unbound_session_count), coverage: row.coverage ?? {}, fieldDifferences: Array.isArray(row.field_differences) ? row.field_differences : [], invariantResults: row.invariant_results ?? { oneToOne: 'unknown', asrQuality: 'unknown', blockingFormat: 'unknown', termConflicts: 'unknown' }, snapshotDigest: row.snapshot_digest, requestId: row.request_id, startedAt: row.started_at ? iso(row.started_at) : null, completedAt: row.completed_at ? iso(row.completed_at) : null, createdAt: iso(row.created_at) }; }
  async getImpact(id: string) { const r = await this.database.query('SELECT * FROM strategy_runtime_impact_runs WHERE id=$1', [id]); if (!r.rows[0]) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_IMPACT_NOT_FOUND', '影响检查不存在', 404); return this.toImpact(r.rows[0]); }
  async listQueuedImpactIds(): Promise<string[]> { const r = await this.database.query<{ id: string }>(`SELECT id FROM strategy_runtime_impact_runs WHERE status='queued' OR (status='running' AND (lease_expires_at IS NULL OR lease_expires_at < CURRENT_TIMESTAMP)) ORDER BY created_at ASC,id ASC LIMIT 20`); return r.rows.map((row) => row.id); }
  private evaluateSnapshot(snapshot: any): RuntimeEvaluation {
    const samples = Array.isArray(snapshot?.samples) ? snapshot.samples : []; const rulePack = asRulePack(snapshot?.candidateRulePack); const blockers = Array.isArray(snapshot?.blockers) ? [...snapshot.blockers] : [];
    let oneToOne = true; let asrQuality = true; let blockingFormat = true; let termConflicts = true;
    for (const sample of samples) {
      const company = (sample.companyCues ?? []) as AlignmentCue[]; const asr = (sample.asrCues ?? []) as AlignmentCue[]; const groups = alignEpisode(company, asr, rulePack); if (!groups.length || groups.some((group) => group.kind !== 'one_to_one')) oneToOne = false;
      if (sample.asrQualityStatus !== 'pass') asrQuality = false;
      const termEvidence = Array.isArray(sample.termEvidence) ? sample.termEvidence : []; if (termEvidence.some((evidence: any) => evidence.conflict)) termConflicts = false;
      for (const group of groups) { const target = group.companyCues[0] ?? null; const system = effectiveSystemDecision({ kind: group.kind, policy: 'company_primary', companyCue: target, asrCues: group.asrCues }); const timing = target ?? group.asrCues[0]; const issues = scanFormatIssues(system.text, rulePack, timing ? { startMs: timing.startMs, endMs: target?.endMs ?? group.asrCues.at(-1)!.endMs, videoDurationMs: sample.videoDurationMs ?? null } : undefined); if (issues.some((issue) => issue.blocking)) { blockingFormat = false; blockers.push('固定样本存在阻断格式问题'); } }
    }
    const evaluated = samples.length > 0; return { blockers: [...new Set(blockers)], invariants: evaluated ? { oneToOne: oneToOne ? 'pass' : 'fail', asrQuality: asrQuality ? 'pass' : 'fail', blockingFormat: blockingFormat ? 'pass' : 'fail', termConflicts: termConflicts ? 'pass' : 'fail' } : { oneToOne: 'unknown', asrQuality: 'unknown', blockingFormat: 'unknown', termConflicts: 'unknown' }, affectedSessionCount: new Set(samples.map((sample: any) => sample.sessionId)).size, sampleCount: samples.length };
  }
  async claimImpact(impactRunId: string, workerId: string): Promise<{ attemptId: string; snapshotInput: any } | null> {
    const client = await this.database.connect();
    try {
      await client.query('BEGIN'); await this.lock(client, impactRunId);
      const run = await client.query<any>('SELECT id,status,lease_expires_at,snapshot_input FROM strategy_runtime_impact_runs WHERE id=$1 FOR UPDATE', [impactRunId]); if (!run.rows[0] || ['succeeded', 'failed', 'unknown'].includes(run.rows[0].status)) { await client.query('ROLLBACK'); return null; }
      if (run.rows[0].status === 'running' && run.rows[0].lease_expires_at && new Date(run.rows[0].lease_expires_at) >= new Date()) { await client.query('ROLLBACK'); return null; }
      if (run.rows[0].status === 'running') await client.query("UPDATE strategy_runtime_impact_attempts SET status='unknown',completed_at=CURRENT_TIMESTAMP,lease_owner=NULL,lease_expires_at=NULL WHERE impact_run_id=$1 AND status='running'", [impactRunId]);
      const attemptId = randomUUID(); await client.query(`INSERT INTO strategy_runtime_impact_attempts(id,impact_run_id,status,lease_owner,lease_expires_at,request_id,started_at) VALUES($1,$2,'running',$3,CURRENT_TIMESTAMP + interval '30 seconds',$4,CURRENT_TIMESTAMP)`, [attemptId, impactRunId, workerId, randomUUID()]);
      await client.query(`UPDATE strategy_runtime_impact_runs SET status='running',lease_owner=$2,lease_expires_at=CURRENT_TIMESTAMP + interval '30 seconds',started_at=COALESCE(started_at,CURRENT_TIMESTAMP) WHERE id=$1`, [impactRunId, workerId]); await client.query('COMMIT'); return { attemptId, snapshotInput: run.rows[0].snapshot_input };
    } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
  }
  async finalizeImpact(impactRunId: string, attemptId: string, workerId: string, outcome: { status: 'succeeded' | 'unknown'; blockers: string[]; invariants: RuntimeInvariantResults; affectedSessionCount: number; sampleCount: number }) {
    const client = await this.database.connect();
    try {
      await client.query('BEGIN'); const run = await client.query<any>(`UPDATE strategy_runtime_impact_runs SET status=$2,lease_owner=NULL,lease_expires_at=NULL,completed_at=CURRENT_TIMESTAMP,failure_reason=$3,blockers=$4,invariant_results=$5,affected_session_count=$6,sample_count=$7 WHERE id=$1 AND status='running' AND lease_owner=$8 RETURNING *`, [impactRunId, outcome.status, outcome.status === 'unknown' ? '固定快照执行失败' : null, JSON.stringify(outcome.blockers), JSON.stringify(outcome.invariants), outcome.affectedSessionCount, outcome.sampleCount, workerId]); if (!run.rows[0]) { await client.query('ROLLBACK'); return { processed: false, status: 'stale' as const }; }
      const attempt = await client.query(`UPDATE strategy_runtime_impact_attempts SET status=$2,lease_owner=NULL,lease_expires_at=NULL,completed_at=CURRENT_TIMESTAMP WHERE id=$1 AND status='running' AND lease_owner=$3 RETURNING id`, [attemptId, outcome.status, workerId]); if (!attempt.rows[0]) throw new Error('影响检查尝试租约已变化');
      const final = this.toImpact(run.rows[0]); await client.query('UPDATE system_control_commands SET response_snapshot=$2 WHERE stable_command_key=$1 AND command_kind=\'strategy_runtime_impact\'', [impactRunId, final]); await client.query('COMMIT'); return { processed: true, status: final.status, blockers: final.blockers, invariants: final.invariantResults };
    } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
  }
  async processImpact(impactRunId: string, workerId: string) {
    const claim = await this.claimImpact(impactRunId, workerId); if (!claim) return { processed: false };
    try { return await this.finalizeImpact(impactRunId, claim.attemptId, workerId, { status: 'succeeded', ...this.evaluator(claim.snapshotInput) }); }
    catch { try { return await this.finalizeImpact(impactRunId, claim.attemptId, workerId, { status: 'unknown', blockers: [], invariants: { oneToOne: 'unknown', asrQuality: 'unknown', blockingFormat: 'unknown', termConflicts: 'unknown' }, affectedSessionCount: 0, sampleCount: 0 }); } catch { return { processed: true, status: 'unknown' as const }; } }
  }

  async approve(input: { approvalId: string; impactRunId: string; strategyVersionId: string; idempotencyKey: string; requestId: string; principal: SystemControlPrincipal }) {
    if (![input.approvalId, input.impactRunId, input.strategyVersionId].every(isUuid) || input.idempotencyKey.trim().length < 8) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_INVALID_COMMAND', '批准命令身份无效', 422);
    const requestHash = digest({ approvalId: input.approvalId, impactRunId: input.impactRunId, strategyVersionId: input.strategyVersionId }); const client = await this.database.connect();
    try {
      await client.query('BEGIN'); await this.lock(client, input.approvalId); await this.lock(client, input.idempotencyKey); const stableRow = await client.query('SELECT request_hash,response_snapshot FROM system_control_commands WHERE stable_command_key=$1 FOR UPDATE', [input.approvalId]); if (stableRow.rows[0]) { if (stableRow.rows[0].request_hash !== requestHash) throw commandConflict('SYSTEM_CONTROL_STRATEGY_APPROVAL_ID_REUSED', '批准身份已被其他请求使用'); await client.query('COMMIT'); return { approval: stableRow.rows[0].response_snapshot, replay: true }; }
      const impact = await client.query('SELECT * FROM strategy_runtime_impact_runs WHERE id=$1 AND strategy_version_id=$2 FOR SHARE', [input.impactRunId, input.strategyVersionId]); if (!impact.rows[0]) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_IMPACT_NOT_FOUND', '影响检查不存在', 404); if (impact.rows[0].status !== 'succeeded' || (impact.rows[0].blockers ?? []).length || Object.values(impact.rows[0].invariant_results ?? {}).some((v) => v !== 'pass')) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_IMPACT_NOT_APPROVABLE', '影响检查未满足批准门', 409);
      const version = await client.query(`SELECT v.content_digest,v.runtime_status FROM strategy_artifact_versions v JOIN strategy_artifacts a ON a.id=v.artifact_id WHERE v.id=$1 FOR UPDATE`, [input.strategyVersionId]); if (!version.rows[0]) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_VERSION_NOT_FOUND', '策略版本不存在', 404); if (impact.rows[0].content_digest !== version.rows[0].content_digest) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_CONTENT_CHANGED', '影响检查内容摘要已变化', 409);
      await client.query("UPDATE strategy_artifact_versions SET runtime_status='approved',runtime_updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND runtime_status IN ('draft','testing','impact_checked')", [input.strategyVersionId]);
      const inserted = await client.query(`INSERT INTO strategy_runtime_approvals(id,impact_run_id,strategy_version_id,content_digest,request_id,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`, [input.approvalId, input.impactRunId, input.strategyVersionId, version.rows[0].content_digest, input.requestId, input.principal.subject]); const approval = { approvalId: inserted.rows[0].id, impactRunId: inserted.rows[0].impact_run_id, strategyVersionId: inserted.rows[0].strategy_version_id, status: 'approved' as const, requestId: inserted.rows[0].request_id, createdAt: iso(inserted.rows[0].created_at) };
      await this.command(client, input.approvalId, 'strategy_runtime_approval', input.idempotencyKey, requestHash, input.strategyVersionId, approval); await this.audit(client, input, 'strategy_runtime_approval', input.strategyVersionId, input.idempotencyKey, { impactRunId: input.impactRunId }); await client.query('COMMIT'); return { approval, replay: false };
    } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); }
  }
  async getApproval(id: string) { return this.getCommandVersion(id, 'strategy_runtime_approval', 'SYSTEM_CONTROL_STRATEGY_APPROVAL_NOT_FOUND', '批准命令不存在') as Promise<any>; }

  async release(input: { releaseCommandId: string; action: 'publish' | 'rollback'; strategyVersionId: string; expectedPreviousStrategyVersionId: string | null; impactRunId: string; approvalId: string; contentDigest: string; idempotencyKey: string; requestId: string; principal: SystemControlPrincipal }) {
    if (![input.releaseCommandId, input.strategyVersionId].every(isUuid) || input.idempotencyKey.trim().length < 8) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_INVALID_COMMAND', '发布命令身份无效', 422);
    if (input.expectedPreviousStrategyVersionId !== null && !isUuid(input.expectedPreviousStrategyVersionId)) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_INVALID_COMMAND', '期望旧版本身份无效', 422);
    if (!isUuid(input.impactRunId) || !isUuid(input.approvalId) || !/^[0-9a-f]{64}$/.test(input.contentDigest)) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_INVALID_COMMAND', '发布证据身份无效', 422);
    const requestHash = digest({ releaseCommandId: input.releaseCommandId, action: input.action, strategyVersionId: input.strategyVersionId, expectedPreviousStrategyVersionId: input.expectedPreviousStrategyVersionId, impactRunId: input.impactRunId, approvalId: input.approvalId, contentDigest: input.contentDigest }); const client = await this.database.connect();
    try {
      await client.query('BEGIN'); await this.lock(client, input.releaseCommandId); await this.lock(client, MODULE); await this.lock(client, input.idempotencyKey); const stableRow = await client.query<{ request_hash: string; response_snapshot: SystemControlStrategyReleaseCommand }>('SELECT request_hash,response_snapshot FROM system_control_commands WHERE stable_command_key=$1 FOR UPDATE', [input.releaseCommandId]); if (stableRow.rows[0]) { if (stableRow.rows[0].request_hash !== requestHash) throw commandConflict('SYSTEM_CONTROL_STRATEGY_RELEASE_ID_REUSED', '发布命令身份已被其他请求使用'); await client.query('COMMIT'); return { command: stableRow.rows[0].response_snapshot, replay: true }; }
      const version = await client.query(`SELECT v.id,v.content_digest,v.runtime_status,a.origin,a.runtime_module FROM strategy_artifact_versions v JOIN strategy_artifacts a ON a.id=v.artifact_id WHERE v.id=$1 FOR UPDATE`, [input.strategyVersionId]); if (!version.rows[0] || version.rows[0].runtime_module !== MODULE) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_VERSION_NOT_FOUND', '策略版本不存在', 404);
      if (input.contentDigest !== version.rows[0].content_digest) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_CONTENT_CHANGED', '策略内容摘要已变化', 409);
      if (input.action === 'publish' && version.rows[0].runtime_status !== 'approved') throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_VERSION_NOT_APPROVED', '只有已批准策略版本可以发布', 409);
      if (input.action === 'rollback' && !['approved', 'retired'].includes(version.rows[0].runtime_status)) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_VERSION_NOT_ROLLBACKABLE', '恢复目标必须是已批准或历史已退役版本', 409);
      const current = await client.query<{ strategy_version_id: string }>('SELECT strategy_version_id FROM strategy_runtime_active_pointers WHERE module=$1 FOR UPDATE', [MODULE]); const previous = current.rows[0]?.strategy_version_id ?? null; if (previous === input.strategyVersionId) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_ALREADY_ACTIVE', '目标策略已经是当前 active', 409); if (input.expectedPreviousStrategyVersionId !== previous) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_ACTIVE_CHANGED', '当前生效策略已经变化，请刷新后重试', 409); if (input.action === 'rollback' && !previous) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_NO_ACTIVE', '没有可恢复的当前 active 策略', 409);
      const impact = await client.query(`SELECT * FROM strategy_runtime_impact_runs WHERE id=$1 AND strategy_version_id=$2 FOR SHARE`, [input.impactRunId, input.strategyVersionId]); if (!impact.rows[0] || impact.rows[0].status !== 'succeeded' || (impact.rows[0].blockers ?? []).length || impact.rows[0].content_digest !== version.rows[0].content_digest || Object.values(impact.rows[0].invariant_results ?? {}).some((v) => v !== 'pass')) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_IMPACT_STALE', '影响检查事实已经变化，请重新执行影响检查', 409);
      const approval = await client.query('SELECT content_digest FROM strategy_runtime_approvals WHERE id=$1 AND impact_run_id=$2 AND strategy_version_id=$3', [input.approvalId, input.impactRunId, input.strategyVersionId]); if (!approval.rows[0] || approval.rows[0].content_digest !== version.rows[0].content_digest) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_VERSION_NOT_APPROVED', '策略版本缺少服务端批准事实', 409);
      const unbound = await client.query(`SELECT count(*)::int AS count FROM pre_edit_sessions WHERE strategy_version_id IS NULL AND status IN ('preparing','ready','limited')`);
      if (Number(unbound.rows[0]?.count ?? 0) > 0) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_OLD_SESSION_BLOCKED', '存在尚未绑定策略版本的旧前置审改会话', 409);
      if (previous) await client.query("UPDATE strategy_artifact_versions SET runtime_status='retired',runtime_updated_at=CURRENT_TIMESTAMP WHERE id=$1", [previous]); await client.query("UPDATE strategy_artifact_versions SET runtime_status='active',runtime_updated_at=CURRENT_TIMESTAMP WHERE id=$1", [input.strategyVersionId]); await client.query(`INSERT INTO strategy_runtime_active_pointers(module,strategy_version_id,updated_at) VALUES($1,$2,CURRENT_TIMESTAMP) ON CONFLICT(module) DO UPDATE SET strategy_version_id=EXCLUDED.strategy_version_id,updated_at=CURRENT_TIMESTAMP`, [MODULE, input.strategyVersionId]);
      const row = await client.query(`INSERT INTO strategy_runtime_release_commands(id,action,strategy_version_id,previous_strategy_version_id,expected_previous_strategy_version_id,impact_run_id,approval_id,content_digest,idempotency_key,request_hash,status,response_snapshot,request_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'succeeded','{}',$11,$12) RETURNING created_at`, [input.releaseCommandId, input.action, input.strategyVersionId, previous, input.expectedPreviousStrategyVersionId, input.impactRunId, input.approvalId, version.rows[0].content_digest, input.idempotencyKey, requestHash, input.requestId, input.principal.subject]); const command: SystemControlStrategyReleaseCommand = { releaseCommandId: input.releaseCommandId, action: input.action, strategyVersionId: input.strategyVersionId, status: 'succeeded', previousStrategyVersionId: previous, requestId: input.requestId, createdAt: iso(row.rows[0].created_at) }; await client.query('UPDATE strategy_runtime_release_commands SET response_snapshot=$2 WHERE id=$1', [input.releaseCommandId, command]); await client.query('INSERT INTO strategy_runtime_release_events(release_command_id,action,strategy_version_id,previous_strategy_version_id,actor_subject,request_id) VALUES($1,$2,$3,$4,$5,$6)', [input.releaseCommandId, input.action, input.strategyVersionId, previous, input.principal.subject, input.requestId]); await this.command(client, input.releaseCommandId, 'strategy_runtime_release', input.idempotencyKey, requestHash, input.strategyVersionId, command); await this.audit(client, input, `strategy_runtime_${input.action}`, input.strategyVersionId, input.idempotencyKey, { previousStrategyVersionId: previous }); await client.query('COMMIT'); return { command, replay: false };
    } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); }
  }
  async getReleaseCommand(id: string): Promise<SystemControlStrategyReleaseCommand> { const r = await this.database.query<{ response_snapshot: SystemControlStrategyReleaseCommand }>('SELECT response_snapshot FROM strategy_runtime_release_commands WHERE id=$1', [id]); if (!r.rows[0]) throw new SystemControlStrategyRuntimeError('SYSTEM_CONTROL_STRATEGY_RELEASE_NOT_FOUND', '发布命令不存在', 404); return r.rows[0].response_snapshot; }
  async listHistory(query: SystemControlStrategyHistoryQuery): Promise<SystemControlHistory> { const { limit, offset } = parsePage(query); const r = await this.database.query(`SELECT v.id,v.content_digest,v.created_at,v.runtime_updated_at,v.runtime_status AS status,v.base_version_id,v.source,v.evaluation_run_id,v.candidate_digest,a.origin,
      COALESCE((SELECT jsonb_agg(jsonb_build_object('impactRunId',i.id,'status',i.status,'contentDigest',i.content_digest,'snapshotDigest',i.snapshot_digest,'createdAt',i.created_at,'completedAt',i.completed_at) ORDER BY i.created_at ASC,i.id ASC) FROM strategy_runtime_impact_runs i WHERE i.strategy_version_id=v.id),'[]'::jsonb) AS impacts,
      COALESCE((SELECT jsonb_agg(jsonb_build_object('approvalId',ap.id,'impactRunId',ap.impact_run_id,'contentDigest',ap.content_digest,'createdAt',ap.created_at) ORDER BY ap.created_at ASC,ap.id ASC) FROM strategy_runtime_approvals ap WHERE ap.strategy_version_id=v.id),'[]'::jsonb) AS approvals,
      COALESCE((SELECT jsonb_agg(jsonb_build_object('eventId',e.id,'releaseCommandId',e.release_command_id,'action',e.action,'strategyVersionId',e.strategy_version_id,'previousStrategyVersionId',e.previous_strategy_version_id,'createdAt',e.created_at) ORDER BY e.created_at ASC,e.id ASC) FROM strategy_runtime_release_events e WHERE e.strategy_version_id=v.id),'[]'::jsonb) AS release_events,
      count(*) OVER() AS total FROM strategy_artifact_versions v JOIN strategy_artifacts a ON a.id=v.artifact_id WHERE a.runtime_module=$1 ORDER BY v.created_at DESC,v.id DESC LIMIT $2 OFFSET $3`, [MODULE, limit, offset]); const total = r.rows[0] ? Number(r.rows[0].total) : Number((await this.database.query('SELECT count(*)::int AS total FROM strategy_artifact_versions v JOIN strategy_artifacts a ON a.id=v.artifact_id WHERE a.runtime_module=$1', [MODULE])).rows[0]?.total ?? 0); return { items: r.rows.map((row: any) => ({ strategyVersionId: row.id, origin: row.origin, status: row.status, contentDigest: row.content_digest, baseVersionId: row.base_version_id ?? null, source: row.source ?? 'manual', evaluationRunId: row.evaluation_run_id ?? null, candidateDigest: row.candidate_digest ?? null, impacts: row.impacts ?? [], approvals: row.approvals ?? [], releaseEvents: row.release_events ?? [], createdAt: iso(row.created_at), updatedAt: iso(row.runtime_updated_at ?? row.created_at) })), total, limit, offset }; }
}
