export const modules = [
  {
    id: 'projects',
    scope: 'global',
    title: '项目中心',
    route: '/projects',
    group: 'project',
    order: 10,
    status: 'active',
  },
  {
    id: 'uploads',
    scope: 'global',
    title: '上传任务',
    route: '/uploads',
    group: 'project',
    order: 20,
    status: 'active',
  },
  {
    id: 'recycle-bin',
    scope: 'global',
    title: '项目回收站',
    route: '/recycle-bin',
    group: 'project',
    order: 30,
    status: 'active',
  },
  {
    id: 'tasks',
    scope: 'global',
    title: '任务中心',
    route: '/tasks',
    group: 'job',
    order: 10,
    status: 'active',
  },
  {
    id: 'deliveries',
    scope: 'global',
    title: '交付产品库',
    route: '/deliveries',
    group: 'project',
    order: 40,
    status: 'active',
  },
  {
    id: 'project-materials',
    scope: 'project',
    title: '概览与素材',
    route: '/projects/:projectId/materials',
    group: 'work',
    order: 10,
    status: 'active',
  },
  {
    id: 'project-terms',
    scope: 'project',
    title: '术语',
    route: '/projects/:projectId/terms',
    group: 'work',
    order: 20,
    status: 'active',
  },
  {
    id: 'project-asr',
    scope: 'project',
    title: '中文识别',
    route: '/projects/:projectId/asr',
    group: 'work',
    order: 30,
    status: 'active',
  },
  {
    id: 'project-screen-text',
    scope: 'project',
    title: '画面字',
    route: '/projects/:projectId/screen-text',
    group: 'work',
    order: 40,
    status: 'active',
  },
  {
    id: 'project-pre-review',
    scope: 'project',
    title: '前置审改',
    route: '/projects/:projectId/pre-review',
    group: 'work',
    order: 50,
    status: 'active',
  },
  {
    id: 'project-subtitle-acceptance',
    scope: 'project',
    title: '视频字幕验收',
    route: '/projects/:projectId/subtitle-acceptance',
    group: 'work',
    order: 60,
    status: 'active',
  },
] as const;

export const globalModules = modules.filter((module) => module.scope === 'global');
export const projectModules = modules.filter((module) => module.scope === 'project');
